#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "config.h"
#include "libmio0.h"
#include "mipsdisasm.h"
#include "n64graphics.h"
#include "utils.h"

#define N64SPLIT_VERSION "0.3.1a"

#define GLOBALS_FILE "globals.inc"

typedef struct _arg_config
{
   char input_file[FILENAME_MAX];
   char config_file[FILENAME_MAX];
   char output_dir[FILENAME_MAX];
   float scale;
   int  large_texture;
   int  gen_proc_table;
} arg_config;

typedef enum {
   N64_ROM_INVALID,
   N64_ROM_Z64,
   N64_ROM_V64,
} n64_rom_format;

// default configuration
static const arg_config default_args = 
{
   "", // input filename
   "", // config filename
   "", // output directory
   1024.0f, // scale
   0,  // all textures
   0,  // procedure table
};

// static makefile
#include "n64split.makefile.h"

const char asm_header[] = 
   "# %s disassembly and split file\n"
   "# generated by n64split v%s - N64 ROM splitter\n"
   "\n"
   "# assembler directives\n"
   ".set noat      # allow manual use of $at\n"
   ".set noreorder # don't insert nops after branches\n"
   "\n"
   ".include \"" GLOBALS_FILE "\"\n"
   "\n";

static void print_spaces(FILE *fp, int count)
{
   int i;
   for (i = 0; i < count; i++) {
      fputc(' ', fp);
   }
}

static n64_rom_format n64_rom_type(unsigned char *buf, unsigned int length)
{
   const unsigned char bs[] = {0x37, 0x80, 0x40, 0x12}; // byte-swapped
   const unsigned char be[] = {0x80, 0x37, 0x12, 0x40}; // big-endian
   if (length >= (8 * MB)) {
      if (!memcmp(buf, bs, sizeof(bs))) {
         return N64_ROM_V64;
      }
      if (!memcmp(buf, be, sizeof(be))) {
         return N64_ROM_Z64;
      }
   }
   return N64_ROM_INVALID;
}

static void write_behavior(FILE *out, unsigned char *data, rom_config *config, int s)
{
   char label[128];
   unsigned int a, i;
   unsigned int len;
   unsigned int val;
   int beh_i;
   split_section *sec;
   behavior *beh;
   sec = &config->sections[s];
   beh = sec->extra;
   a = sec->start;
   beh_i = 0;
   while (a < sec->end) {
      if (beh_i < sec->extra_len) {
         unsigned int offset = a - sec->start;
         if (offset == beh[beh_i].offset) {
            fprintf(out, "%s: # %04X\n", beh[beh_i].name, beh[beh_i].offset);
            beh_i++;
         } else if (offset > beh[beh_i].offset) {
            ERROR("Warning: skipped behavior %04X \"%s\"\n", beh[beh_i].offset, beh[beh_i].name);
            beh_i++;
         }
      }
      switch (data[a]) {
         case 0x02:
         case 0x04:
         case 0x0C:
         case 0x14:
         case 0x23:
         case 0x27:
         case 0x2A:
         case 0x2F:
         case 0x37:
            len = 8;
            break;
         case 0x1C:
         case 0x29:
         case 0x2B:
         case 0x2C:
            len = 12;
            break;
         case 0x30:
            len = 20;
            break;
         default:
            len = 4;
            break;
      }
      val = read_u32_be(&data[a]);
      fprintf(out, ".word 0x%08X", val);
      switch(data[a]) {
         case 0x0C: // behavior 0x0C is a function pointer
            val = read_u32_be(&data[a+4]);
            fill_addr_label(config, val, label, -1);
            fprintf(out, ", %s\n", label);
            break;
         case 0x02: // jump to another behavior
         case 0x04: // jump to segmented address
         case 0x1C: // sub-objects
         case 0x29: // sub-objects
         case 0x2C: // sub-objects
            for (i = 4; i < len-4; i += 4) {
               val = read_u32_be(&data[a+i]);
               fprintf(out, ", 0x%08X", val);
            }
            val = read_u32_be(&data[a+len-4]);
            fill_addr_label(config, val, label, -1);
            fprintf(out, ", %s\n", label);
            break;
         default:
            for (i = 4; i < len; i += 4) {
               val = read_u32_be(&data[a+i]);
               fprintf(out, ", 0x%08X", val);
            }
            fprintf(out, "\n");
            break;
      }
      a += len;
   }
}

static void write_geolayout(FILE *out, unsigned char *data, unsigned int start, unsigned int end, rom_config *config)
{
   char label[128];
   unsigned int a = start;
   int indent;
   int len;
   int i;
   indent = 0;
   // TODO: process function pointers and other geo layout references
   (void)config;
   while (a < end) {
      if (indent == 0) {
         switch (data[a]) {
            case 0x16:
            case 0x20:
               fprintf(out, "# %04X\n", a);
            default: break;
         }
      }
      switch (data[a]) {
         case 0x00: // end
         case 0x01:
         case 0x03:
         case 0x04:
         case 0x05:
         case 0x09:
         case 0x0B:
         case 0x0C:
         case 0x17:
         case 0x20:
            len = 4;
            break;
         case 0x02:
         case 0x0D:
         case 0x0E:
         case 0x12:
         case 0x14:
         case 0x15:
         case 0x16:
         case 0x18:
         case 0x19:
            len = 8;
            break;
         case 0x08:
         case 0x13:
         case 0x1C:
            len = 12;
            break;
         case 0x10:
         case 0x1F:
            len = 16;
            break;
         case 0x0F:
            len = 20;
            break;
         case 0x0A:
            len = 8;
            if (data[a+1]) {
               len += 4;
            }
            break;
         case 0x11:
         case 0x1D:
            len = 8;
            if (data[a+1] & 0x80) {
               len += 4;
            }
            break;
         default:
            len = 4;
            ERROR("WHY? %06X %2X\n", a, data[a]);
      }
      if (data[a] == 0x05 && indent > 1) {
         indent -= 2;
      }
      if (data[a] == 0x01) {
         indent = 0;
      }
      fprintf(out, ".word ");
      print_spaces(out, indent);
      switch (data[a]) {
         case 0x0A:
            fprintf(out, "0x%08X", read_u32_be(&data[a]));
            fprintf(out, ", 0x%08X", read_u32_be(&data[a+4]));
            if (len > 8) {
               fill_addr_label(config, read_u32_be(&data[a+8]), label, -1);
               fprintf(out, ", %s", label);
            }
            break;
         case 0x0E:
         case 0x0F:
         case 0x18:
         case 0x19:
         case 0x1C:
            // these all have a function pointer in the last word
            fprintf(out, "0x%08X", read_u32_be(&data[a]));
            for (i = 4; i < len-4; i+=4) {
               fprintf(out, ", 0x%08X", read_u32_be(&data[a+i]));
            }
            fill_addr_label(config, read_u32_be(&data[a+len-4]), label, -1);
            fprintf(out, ", %s", label);
            break;
         default:
            fprintf(out, "0x%08X", read_u32_be(&data[a]));
            for (i = 4; i < len; i+=4) {
               fprintf(out, ", 0x%08X", read_u32_be(&data[a+i]));
            }
            break;
      }
      fprintf(out, "\n");
      if (data[a] == 0x04) {
         indent += 2;
      }
      a += len;
   }
}

static void write_level(FILE *out, unsigned char *data, rom_config *config, int s)
{
   char start_label[128];
   char end_label[128];
   char dst_label[128];
   split_section *sec;
   unsigned int ptr_start;
   unsigned int ptr_end;
   unsigned int dst;
   unsigned int a;
   int i;
   int beh_i;

   sec = &config->sections[s];

   beh_i = -1;
   // see if there is a behavior section
   for (i = 0; i < config->section_count; i++) {
      if (config->sections[i].type == TYPE_BEHAVIOR) {
         beh_i = i;
         break;
      }
   }
   a = sec->start;
   while (a < sec->end) {
      // length = 0 ends level script
      if (data[a+1] == 0) {
         break;
      }
      switch (data[a]) {
         case 0x00: // load and jump from ROM into a RAM segment
         case 0x01: // load and jump from ROM into a RAM segment
         case 0x17: // copy uncompressed data from ROM to a RAM segment
         case 0x18: // decompress MIO0 data from ROM and copy it into a RAM segment
         case 0x1A: // decompress MIO0 data from ROM and copy it into a RAM segment (for texture only segments?)
            ptr_start = read_u32_be(&data[a+4]);
            ptr_end = read_u32_be(&data[a+8]);
            fill_addr_label(config, ptr_start, start_label, 0);
            fill_addr_label(config,   ptr_end,   end_label, 1);
            fprintf(out, ".word 0x");
            for (i = 0; i < 4; i++) {
               fprintf(out, "%02X", data[a+i]);
            }
            if (0 == strcmp("behavior_data", start_label)) {
               fprintf(out, ", __load_%s, __load_%s", start_label, end_label);
            } else {
               fprintf(out, ", %s, %s", start_label, end_label);
            }
            for (i = 12; i < data[a+1]; i++) {
               if ((i & 0x3) == 0) {
                  fprintf(out, ", 0x");
               }
               fprintf(out, "%02X", data[a+i]);
            }
            fprintf(out, "\n");
            break;
         case 0x11: // call function
         case 0x12: // call function
            ptr_start = read_u32_be(&data[a+0x4]);
            fill_addr_label(config, ptr_start, start_label, -1);
            fprintf(out, ".word 0x%08X, %s # %08X\n", read_u32_be(&data[a]), start_label, ptr_start);
            break;
         case 0x16: // load ASM into RAM
            dst       = read_u32_be(&data[a+0x4]);
            ptr_start = read_u32_be(&data[a+0x8]);
            ptr_end   = read_u32_be(&data[a+0xc]);
            fill_addr_label(config, dst, dst_label, 0);
            fill_addr_label(config, ptr_start, start_label, 0);
            fill_addr_label(config, ptr_end, end_label, 1);
            fprintf(out, ".word 0x");
            for (i = 0; i < 4; i++) {
               fprintf(out, "%02X", data[a+i]);
            }
            fprintf(out, ", %s, %s, %s\n", dst_label, start_label, end_label);
            break;
         case 0x25: // load mario object with behavior
         case 0x24: // load object with behavior
            fprintf(out, ".word 0x%08X", read_u32_be(&data[a]));
            for (i = 4; i < data[a+1]-4; i+=4) {
               fprintf(out, ", 0x%08X", read_u32_be(&data[a+i]));
            }
            dst = read_u32_be(&data[a+i]);
            if (beh_i >= 0) {
               unsigned int offset = dst & 0xFFFFFF;
               behavior *beh = config->sections[beh_i].extra;
               for (i = 0; i < config->sections[beh_i].extra_len; i++) {
                  if (offset == beh[i].offset) {
                     fprintf(out, ", %s", beh[i].name);
                     break;
                  }
               }
               if (i >= config->sections[beh_i].extra_len) {
                  ERROR("Error: cannot find behavior %04X needed at offset %X\n", offset, a);
               }
            } else {
               fprintf(out, ", 0x%08X", dst);
            }
            fprintf(out, "\n");
            break;
         default:
            fprintf(out, ".word 0x%08X", read_u32_be(&data[a]));
            for (i = 4; i < data[a+1]; i+=4) {
               fprintf(out, ", 0x%08X", read_u32_be(&data[a+i]));
            }
            fprintf(out, "\n");
            break;
      }
      a += data[a+1];
   }
   // align to next 16-byte boundary
   if (a & 0x0F) {
      fprintf(out, "# begin %s alignment 0x%X\n", sec->label, a);
      fprintf(out, ".byte ");
      fprint_hex_source(out, &data[a], ALIGN(a, 16) - a);
      fprintf(out, "\n");
      a = ALIGN(a, 16);
   }
   // remaining is geo layout script
   fprintf(out, "# begin %s geo 0x%X\n", sec->label, a);
   write_geolayout(out, &data[sec->start], a - sec->start, sec->end - sec->start, config);
}

static int disassemble_dummy(FILE *out, rom_config *config, unsigned char *data, unsigned int start, unsigned int end)
{
   unsigned int instr;
   unsigned int i;
   unsigned int len = end - start;
   unsigned int rom_start = ram_to_rom(config, start);
   unsigned int rom_end = ram_to_rom(config, end);
   int allnops = 1;
   // first check all nops
   for (i = rom_start; i < rom_end; i += 4) {
      instr = read_u32_be(&data[i]);
      if (instr != 0x0) {
         allnops = 0;
         break;
      }
   }
   if (allnops) {
      fprintf(out, "\n# alignment");
      for (i = 0; i < len; i += 4) {
         if (i % 0x10 == 0) {
            fprintf(out, "\n.word 0x00000000");
         } else {
            fprintf(out, ", 0x00000000");
         }
      }
      fprintf(out, "\n");
      return 1;
   }
   // ensure multiple of 4 (also takes care of < 4)
   if (len & 0x3) return 0;
   for (i = rom_start; i < rom_end; i += 4) {
      instr = read_u32_be(&data[i]);
      if (instr != 0x03e00008 && instr != 0x00000000) return 0;
   }
   fprintf(out, "\ndummy%08X:\n", start);
   for (i = rom_start; i < rom_end; i += 4) {
      instr = read_u32_be(&data[i]);
      switch (instr) {
         case 0x03e00008: fprintf(out, "  jr    $ra\n"); break;
         case 0x00000000: fprintf(out, "  nop\n"); break;
      }
   }
   return 1;
}

static void disassemble_section(FILE *out, unsigned char *data, long len, split_section *sec, proc_table *procs, rom_config *config)
{
   // disassemble all the procedures
   unsigned int ram_address;
   unsigned int prev_end;
   unsigned int end_address;
   int start_proc;
   int proc_idx;
   // find first procedure in section
   prev_end = rom_to_ram(config, sec->start);
   for (start_proc = 0; start_proc < procs->count; start_proc++) {
      if (procs->procedures[start_proc].start >= prev_end) {
         break;
      }
   }
   // disassemble each procedure
   end_address = rom_to_ram(config, sec->end);
   for (proc_idx = start_proc; proc_idx < procs->count; proc_idx++) {
      ram_address = procs->procedures[proc_idx].start;
      // TODO: this is a workaround for inner procedures
      switch (ram_address) {
         // SM64 (U)
         case 0x80327B98: // proc_80327B98
         case 0x80327C80: // __osEnqueueAndYield
         case 0x80327D10: // __osEnqueueThread
         case 0x80327D58: // __osPopThread
         case 0x80327D68: // __osDispatchThread
         // SM64 (J)
         case 0x80326D00: // __osEnqueueAndYield
         case 0x80326D90: // __osEnqueueThread
         case 0x80326DD8: // __osPopThread
         case 0x80326DE8: // __osDispatchThread
            continue;
         default: break;
      }
      if (ram_address > end_address) {
         ram_address = end_address;
      }
      if (ram_address > prev_end) {
         int is_dummy = disassemble_dummy(out, config, data, prev_end, ram_address);
         if (!is_dummy) {
            fprintf(out, "\n# unknown assembly section %X-%X (%06X-%06X) [%X]",
                  prev_end, ram_address, ram_to_rom(config, prev_end), ram_to_rom(config, ram_address), ram_address - prev_end);
            unsigned int a = ram_to_rom(config, prev_end);
            int count = 0;
            unsigned int rom_address = ram_to_rom(config, ram_address);
            int newline = 0;
            while (a < rom_address) {
               unsigned int val = read_u32_be(&data[a]);
               if (val == 0x03e00008) {
                  newline = 2;
               }
               if ((count % 4) == 0) {
                  fprintf(out, "\n.word 0x%08x", val);
               } else {
                  fprintf(out, ", 0x%08x", val);
               }
               a += 4;
               count++;
               if (newline) {
                  newline--;
                  if (!newline) {
                     count = 0;
                     fprintf(out, "\n# %X (%06X)", rom_to_ram(config, a), a);
                  }
               }
            }
            fprintf(out, "\n# end unknown section\n");
         }
      }
      if (ram_address < prev_end) {
         ERROR("Warning: %08X < %08X\n", ram_address, prev_end);
      }
      if (ram_address == end_address) {
         break;
      }
      disassemble_proc(out, data, len, &procs->procedures[proc_idx], config);
      prev_end = procs->procedures[proc_idx].end;
      if (prev_end >= end_address) {
         break;
      }
   }
}

static void parse_music_sequences(FILE *out, unsigned char *data, split_section *sec, arg_config *args, char *makeheader)
{
#define MUSIC_SUBDIR    "music"
   typedef struct {
      unsigned start;
      unsigned length;
   } sequence;
   typedef struct {
      unsigned revision;
      unsigned count;
      sequence *seq;
   } sequence_bank;

   char music_dir[FILENAME_MAX];
   char m64_file[FILENAME_MAX];
   char m64_file_rel[FILENAME_MAX];
   char seq_name[128];
   char maketmp[FILENAME_MAX];
   sequence_bank seq_bank = {0};
   unsigned i;

   sprintf(music_dir, "%s/%s", args->output_dir, MUSIC_SUBDIR);
   make_dir(music_dir);

   seq_bank.revision = read_u16_be(&data[sec->start]);
   seq_bank.count = read_u16_be(&data[sec->start+2]);
   if (seq_bank.count > 0) {
      seq_bank.seq = malloc(seq_bank.count * sizeof(*seq_bank.seq));
      for (i = 0; i < seq_bank.count; i++) {
         seq_bank.seq[i].start = read_u32_be(&data[sec->start+i*8+4]);
         seq_bank.seq[i].length = read_u32_be(&data[sec->start+i*8+8]);
      }
   }

   fprintf(out, "\n# music sequence table\n");
   fprintf(out, "music_sequence_table_header:\n");
   fprintf(out, ".hword %d, (music_sequence_table_end - music_sequence_table) / 8\n", seq_bank.revision);
   fprintf(out, "music_sequence_table:\n");
   for (i = 0; i < seq_bank.count; i++) {
      sprintf(seq_name, "seq_%02X", i);
      fprintf(out, ".word (%s - music_sequence_table_header), (%s_end - %s) # 0x%05X, 0x%04X\n",
              seq_name, seq_name, seq_name, seq_bank.seq[i].start, seq_bank.seq[i].length);
   }
   fprintf(out, "music_sequence_table_end:\n");
   fprintf(out, "\n.align 4, 0x01\n");
   for (i = 0; i < seq_bank.count; i++) {
      sprintf(seq_name, "seq_%02X", i);
      fprintf(out, "\n%s:", seq_name);

      sprintf(m64_file, "%s/%s.m64", music_dir, seq_name);
      write_file(m64_file, &data[sec->start + seq_bank.seq[i].start], seq_bank.seq[i].length);

      sprintf(m64_file_rel, "%s/%s.m64", MUSIC_SUBDIR, seq_name);
      fprintf(out, "\n.incbin \"%s\"\n", m64_file_rel);

      // append to Makefile
      sprintf(maketmp, " \\\n$(MUSIC_DIR)/%s.m64", seq_name);
      strcat(makeheader, maketmp);

      fprintf(out, "%s_end:\n", seq_name);
   }

   // free used memory
   if (seq_bank.count > 0) {
      free(seq_bank.seq);
   }
}

static void parse_instrument_set(FILE *out, unsigned char *data, split_section *sec)
{
   unsigned *instrument_set;
   unsigned count;
   unsigned i, cur;

   count = sec->extra_len;
   // each sequence has its own instrument set defined by offsets table
   instrument_set = malloc(count * sizeof(*instrument_set));
   for (i = 0; i < count; i++) {
      instrument_set[i] = read_u16_be(&data[sec->start + 2*i]);
   }
   fprintf(out, "\ninstrument_sets:\n");
   for (i = 0; i < count; i++) {
      fprintf(out, ".hword instrument_set_%02X - instrument_sets # 0x%04X\n", i, instrument_set[i]);
   }

   // output each instrument set
   cur = 0;
   for (i = 2*count; sec->start + i < sec->end; i++) {
      unsigned char val = data[sec->start + i];
      if (instrument_set[cur] == i) {
         fprintf(out, "\ninstrument_set_%02X:\n.byte 0x%02X", cur, val);
         cur++;
      } else {
         fprintf(out, ", 0x%02X", val);
      }
   }
   fprintf(out, "\ninstrument_sets_end:\n");
}

static void generate_globals(arg_config *args, rom_config *config)
{
   char globalfilename[FILENAME_MAX];
   FILE *fglobal;
   int i;
   sprintf(globalfilename, "%s/%s", args->output_dir, GLOBALS_FILE);
   fglobal = fopen(globalfilename, "w");
   if (fglobal == NULL) {
      ERROR("Error opening %s\n", globalfilename);
      exit(3);
   }
   fprintf(fglobal, "# globally accessible functions and data\n"
                    "# these will be accessible by C code and show up in the .map file\n\n");
   for (i = 0; i < config->label_count; i++) {
      fprintf(fglobal, ".global %s\n", config->labels[i].name);
   }
   fprintf(fglobal, "\n");

   fclose(fglobal);
}

static void generate_ld_script(arg_config *args, rom_config *config)
{
   char ldfilename[FILENAME_MAX];
   FILE *fld;
   int i;
   sprintf(ldfilename, "%s/%s.ld", args->output_dir, config->basename);
   fld = fopen(ldfilename, "w");
   if (fld == NULL) {
      ERROR("Error opening %s\n", ldfilename);
      exit(3);
   }
   fprintf(fld,
"/* %s linker script\n"
" * generated by n64split v%s - N64 ROM splitter */\n"
"\n"
"OUTPUT_FORMAT (\"elf32-bigmips\", \"elf32-bigmips\", \"elf32-littlemips\")\n"
"OUTPUT_ARCH (mips)\n"
"\n"
"SECTIONS\n"
"{\n"
"   /* header and boot */\n"
"   .header 0x0 : AT(0x0) {\n"
"      * (.header);\n"
"      * (.boot);\n"
"   }\n"
"\n"
"   /* load MIO0 and level data at 0x800000 */\n"
"   .rodata 0x800000 : {\n"
"      FILL (0x01) /* fill unused with 0x01 */\n"
"      * (.mio0);\n"
"      * (.rodata);\n"
"      * (.data);\n"
"      * (.MIPS.abiflags);\n"
"      . = ALIGN(0x10);\n"
"   }\n"
"\n"
"   /* use segmented addressing for behaviors */\n"
"   .behavior 0x13000000 : AT( LOADADDR(.rodata) + SIZEOF(.rodata) ) {\n"
"      FILL (0x01) /* fill unused with 0x01 */\n"
"      * (.behavior);\n"
"      behavior_length = . - 0x13000000;\n"
"      /* default 4MB data (12MB ROM) */\n"
"      . = 0x400000 - SIZEOF(.rodata);\n"
"   }\n"
"   __load_behavior_data = LOADADDR(.behavior);\n"
"   __load_behavior_data_end = LOADADDR(.behavior) + behavior_length;\n"
"\n", config->name, N64SPLIT_VERSION);
   for (i = 0; i < config->ram_count; i++) {
      unsigned int ram_start = config->ram_table[3*i];
      unsigned int ram_end = config->ram_table[3*i+1];
      unsigned int ram_to_rom = config->ram_table[3*i+2];
      unsigned int length = ram_end - ram_start + 1;
      unsigned int rom_start = ram_start - ram_to_rom;
      unsigned int rom_end = rom_start + length;
      fprintf(fld,
"   /* (0x%08X, 0x%08X, 0x%08X), // %06X-%06X [%X] */\n"
"   .text%08X 0x%08X : AT(0x%06X) {\n"
"      * (.text%08X);\n"
"   }\n"
"\n", ram_start, ram_end, ram_to_rom, rom_start, rom_end, length, ram_start, ram_start, rom_start, ram_start);
   }
   fprintf(fld, "}\n");

   fclose(fld);
}

typedef struct
{
   unsigned type;
   char *name;
} terrain_t;

static terrain_t terrain_table[] =
{
   {0x0000, "normal"},
   {0x0001, "lethal_lava"},
   {0x0005, "hang"},
   {0x000A, "deathfloor"},
   {0x000E, "water_currents"},
   {0x0012, "void"},
   {0x0013, "very_slippery"},
   {0x0014, "slippery"},
   {0x0015, "climbable"},
   {0x0028, "wall"},
   {0x0029, "grass"},
   {0x002A, "unclimbable"},
   {0x002C, "windy"},
   {0x002E, "icy"},
   {0x0030, "flat"},
   {0x0036, "snowy"},
   {0x0037, "snowy"},
   {0x0076, "fence"},
   {0x007B, "vanishing_wall"},
   {0x00FD, "pool_warp"},
};

char *terrain2str(unsigned type)
{
   unsigned i;
   static char retval[16];
   if (0x1B <= type && type <= 0x1E) {
      sprintf(retval, "switch%02X", type);
      return retval;
   } else if (0xA6 <= type && type <= 0xCF) {
      sprintf(retval, "paintingf%02X", type);
      return retval;
   } else if (0xD3 <= type && type <= 0xF8) {
      sprintf(retval, "paintingb%02X", type);
      return retval;
   }
   for (i = 0; i < DIM(terrain_table); i++) {
      if (terrain_table[i].type == type) {
         return terrain_table[i].name;
      }
   }
   sprintf(retval, "%02X", type);
   return retval;
}

void collision2obj(char *binfilename, unsigned int binoffset, char *objfilename, char *name, float scale)
{
   unsigned char *data;
   FILE *fobj;
   long in_size;
   unsigned vcount;
   unsigned tcount;
   unsigned cur_tcount;
   unsigned terrain;
   unsigned v_per_t;
   unsigned processing;
   unsigned offset;
   unsigned i;
   unsigned vidx[3];
   short x, y, z;

   fobj = fopen(objfilename, "w");
   if (fobj == NULL) {
      ERROR("Error opening \"%s\" for writing\n", objfilename);
      exit(EXIT_FAILURE);
   }

   in_size = read_file(binfilename, &data);
   if (in_size <= 0) {
      ERROR("Error reading input file \"%s\"\n", binfilename);
      exit(EXIT_FAILURE);
   }

   offset = binoffset;
   if (data[offset] != 0x00 || data[offset+1] != 0x40) {
      ERROR("Unknown collision data: %08X\n", read_u32_be(data));
      return;
   }

   fprintf(fobj, "# collision model generated from n64split v%s\n"
                 "# level %s %05X\n\n", N64SPLIT_VERSION, name, binoffset);
   vcount = read_u16_be(&data[offset+2]);
   INFO("Loading %u vertices\n", vcount);
   offset += 4;
   for (i = 0; i < vcount; i++) {
      x = read_s16_be(&data[offset + i*6]);
      y = read_s16_be(&data[offset + i*6+2]);
      z = read_s16_be(&data[offset + i*6+4]);
      fprintf(fobj, "v %f %f %f\n", (float)x/scale, (float)y/scale, (float)z/scale);
   }
   offset += vcount*6;
   tcount = 0;
   processing = 1;
   while (processing) {
      terrain = read_u16_be(&data[offset]);
      cur_tcount = read_u16_be(&data[offset+2]);
      if (terrain == 0x41 || terrain > 0xFF) {
         processing = 0;
         break;
      }
      switch (terrain) {
         case 0x0E:
         case 0x2C:
         case 0x24:
         case 0x25:
         case 0x27:
         case 0x2D:
            v_per_t = 4;
            break;
         default:
            v_per_t = 3;
            break;
      }
      fprintf(fobj, "\ng %s_%05X_%s\n", name, binoffset, terrain2str(terrain));

      INFO("Loading %u triangles of terrain %02X\n", cur_tcount, terrain);
      offset += 4;
      for (i = 0; i < cur_tcount; i++) {
         vidx[0] = read_u16_be(&data[offset + i*v_per_t*2]);
         vidx[1] = read_u16_be(&data[offset + i*v_per_t*2+2]);
         vidx[2] = read_u16_be(&data[offset + i*v_per_t*2+4]);
         fprintf(fobj, "f %d %d %d\n", vidx[0]+1, vidx[1]+1, vidx[2]+1);
      }
      tcount += cur_tcount;
      offset += cur_tcount*v_per_t*2;
   }

   fclose(fobj);
   free(data);
}

static void split_file(unsigned char *data, unsigned int length, proc_table *procs, arg_config *args, rom_config *config)
{
#define BIN_SUBDIR      "bin"
#define MIO0_SUBDIR     "bin"
#define TEXTURE_SUBDIR  "textures"
#define GEO_SUBDIR      "geo"
#define LEVEL_SUBDIR    "levels"
#define MODEL_SUBDIR    "models"
#define BEHAVIOR_SUBDIR "."
   char makefile_name[FILENAME_MAX];
   char bin_dir[FILENAME_MAX];
   char mio0_dir[FILENAME_MAX];
   char texture_dir[FILENAME_MAX];
   char geo_dir[FILENAME_MAX];
   char level_dir[FILENAME_MAX];
   char model_dir[FILENAME_MAX];
   char behavior_dir[FILENAME_MAX];
   char asmfilename[FILENAME_MAX];
   char outfilename[FILENAME_MAX];
   char outfilepath[FILENAME_MAX];
   char mio0filename[FILENAME_MAX];
   char maketmp[FILENAME_MAX];
   char start_label[256];
   char *makeheader_mio0;
   char *makeheader_level;
   char *makeheader_music;
   FILE *fasm;
   FILE *fmake;
   int s;
   int i, j;
   unsigned int a;
   unsigned int w, h;
   unsigned int prev_end = 0;
   unsigned int ptr;
   int count;
   int level_alloc;
   split_section *sections = config->sections;

   // create directories
   sprintf(makefile_name, "%s/Makefile.split", args->output_dir);
   sprintf(bin_dir, "%s/%s", args->output_dir, BIN_SUBDIR);
   sprintf(mio0_dir, "%s/%s", args->output_dir, MIO0_SUBDIR);
   sprintf(texture_dir, "%s/%s", args->output_dir, TEXTURE_SUBDIR);
   sprintf(geo_dir, "%s/%s", args->output_dir, GEO_SUBDIR);
   sprintf(level_dir, "%s/%s", args->output_dir, LEVEL_SUBDIR);
   sprintf(model_dir, "%s/%s", args->output_dir, MODEL_SUBDIR);
   sprintf(behavior_dir, "%s/%s", args->output_dir, BEHAVIOR_SUBDIR);
   make_dir(args->output_dir);
   make_dir(bin_dir);
   make_dir(mio0_dir);
   make_dir(texture_dir);
   make_dir(geo_dir);
   make_dir(level_dir);
   make_dir(model_dir);
   make_dir(behavior_dir);

   // open main assembly file and write header
   sprintf(asmfilename, "%s/%s.s", args->output_dir, config->basename);
   fasm = fopen(asmfilename, "w");
   if (fasm == NULL) {
      ERROR("Error opening %s\n", asmfilename);
      exit(3);
   }
   fprintf(fasm, asm_header, config->name, N64SPLIT_VERSION);

   // generate globals include file
   generate_globals(args, config);

   makeheader_music = malloc(100 * strlen(" \\\n$(MUSIC_DIR)/seq_100.m64"));
   sprintf(makeheader_music, "MUSIC_FILES =");

   for (s = 0; s < config->section_count; s++) {
      split_section *sec = &sections[s];

      // error checking
      if (sec->start >= length || sec->end > length) {
         ERROR("Error: section past end: 0x%X, 0x%X (%s) > 0x%X\n",
               sec->start, sec->end, sec->label ? sec->label : "", length);
         exit(4);
      }

      // fill gaps between regions
      if (sec->start != prev_end) {
         int gap_len = sec->start - prev_end;
         INFO("Filling gap before region %d (%d bytes)\n", s, gap_len);
         fprintf(fasm, "# Unknown region %06X-%06X [%X]\n", prev_end, sec->start, gap_len);
         // for small gaps, just output bytes
         if (gap_len <= 0x80) {
            unsigned int group_offset = prev_end;
            while (gap_len > 0) {
               int group_len = MIN(gap_len, 0x10);
               fprintf(fasm, ".byte ");
               fprint_hex_source(fasm, &data[group_offset], group_len);
               fprintf(fasm, "\n");
               gap_len -= group_len;
               group_offset += group_len;
            }
         } else {
            sprintf(outfilename, "%s/%s.%06X.bin", BIN_SUBDIR, config->basename, prev_end);
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);
            write_file(outfilepath, &data[prev_end], gap_len);
            fprintf(fasm, ".incbin \"%s\"\n", outfilename);
         }
         fprintf(fasm, "\n");
      }

      // print section header for new RAM segments
      for (i = 0; i < config->ram_count; i++) {
         if (sec->start == (config->ram_table[3*i] - config->ram_table[3*i+2])) {
            fprintf(fasm, "\n.section .text%08X, \"ax\"\n\n", rom_to_ram(config, sec->start));
         }
      }

      switch (sec->type)
      {
         case TYPE_HEADER:
            INFO("Section header: %X-%X\n", sec->start, sec->end);
            fprintf(fasm, ".section .header, \"a\"\n"
                          ".byte  0x%02X", data[sec->start]);
            for (i = 1; i < 4; i++) {
               fprintf(fasm, ", 0x%02X", data[sec->start + i]);
            }
            fprintf(fasm, " # PI BSD Domain 1 register\n");
            fprintf(fasm, ".word  0x%08X # clock rate setting\n", read_u32_be(&data[sec->start + 0x4]));
            fprintf(fasm, ".word  0x%08X # entry point\n", read_u32_be(&data[sec->start + 0x8]));
            fprintf(fasm, ".word  0x%08X # release\n", read_u32_be(&data[sec->start + 0xc]));
            fprintf(fasm, ".word  0x%08X # checksum1\n", read_u32_be(&data[sec->start + 0x10]));
            fprintf(fasm, ".word  0x%08X # checksum2\n", read_u32_be(&data[sec->start + 0x14]));
            fprintf(fasm, ".word  0x%08X # unknown\n", read_u32_be(&data[sec->start + 0x18]));
            fprintf(fasm, ".word  0x%08X # unknown\n", read_u32_be(&data[sec->start + 0x1C]));
            fprintf(fasm, ".ascii \"");
            fwrite(&data[sec->start + 0x20], 1, 20, fasm);
            fprintf(fasm, "\" # ROM name: 20 bytes\n");
            fprintf(fasm, ".word  0x%08X # unknown\n", read_u32_be(&data[sec->start + 0x34]));
            fprintf(fasm, ".word  0x%08X # cartridge\n", read_u32_be(&data[sec->start + 0x38]));
            fprintf(fasm, ".ascii \"");
            fwrite(&data[sec->start + 0x3C], 1, 2, fasm);
            fprintf(fasm, "\"       # cartridge ID\n");
            fprintf(fasm, ".ascii \"");
            fwrite(&data[sec->start + 0x3E], 1, 1, fasm);
            fprintf(fasm, "\"        # country\n");
            fprintf(fasm, ".byte  0x%02X       # version\n\n", data[sec->start + 0x3F]);
            break;
         case TYPE_BIN:
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(outfilename, "%s/%s.%06X.bin", BIN_SUBDIR, config->basename, sec->start);
            } else {
               sprintf(outfilename, "%s/%s.%06X.%s.bin", BIN_SUBDIR, config->basename, sec->start, sec->label);
            }
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);
            write_file(outfilepath, &data[sec->start], sec->end - sec->start);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "L%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            fprintf(fasm, "%s:\n", start_label);
            fprintf(fasm, ".incbin \"%s\"\n", outfilename);
            fprintf(fasm, "%s_end:\n", start_label);
            break;
         case TYPE_GEO:
         case TYPE_MIO0:
            // fill previous geometry and MIO0 blocks
            fprintf(fasm, ".space 0x%05x, 0x01 # %s\n", sec->end - sec->start, sec->label);
            break;
         case TYPE_PTR:
            INFO("Section ptr: %X-%X\n", sec->start, sec->end);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "Ptr%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            fprintf(fasm, "%s:\n", start_label);
            for (a = sec->start; a < sec->end; a += 4) {
               ptr = read_u32_be(&data[a]);
               fill_addr_label(config, ptr, start_label, -1);
               fprintf(fasm, ".word %s", start_label);
               if (sec->extra_len > 0) {
                  for (i = 1; i < sec->extra_len; i++) {
                     a += 4;
                     ptr = read_u32_be(&data[a]);
                     fill_addr_label(config, ptr, start_label, -1);
                     fprintf(fasm, ", %s", start_label);
                  }
               }
               fprintf(fasm, "\n");
            }
            fprintf(fasm, "\n");
            break;
         case TYPE_ASM:
            INFO("Section asm: %X-%X\n", sec->start, sec->end);
            disassemble_section(fasm, data, length, sec, procs, config);
            break;
         case TYPE_LEVEL:
            // relocate level scripts to .mio0 area
            // TODO: these shouldn't need to be relocated if load offset can be computed
            fprintf(fasm, ".space 0x%05x, 0x01 # %s\n", sec->end - sec->start, sec->label);
            break;
         case TYPE_BEHAVIOR:
            // behaviors are done below
            fprintf(fasm, ".space 0x%05x, 0x01 # %s\n", sec->end - sec->start, sec->label);
            break;
         case TYPE_M64:
            parse_music_sequences(fasm, data, sec, args, makeheader_music);
            break;
         case TYPE_INSTRUMENT_SET:
            parse_instrument_set(fasm, data, sec);
            break;
         default:
            ERROR("Don't know what to do with type %d\n", sec->type);
            exit(1);
            break;
      }
      prev_end = sec->end;
   }

   // put MIO0 in separate data section and generate Makefile
   // allocate some space for the .bin makefile targets
   count = 1024; // header space
   level_alloc = 1024;
   i = strlen(" \\\n$(MIO0_DIR)/");
   j = strlen(" \\\n$(LEVEL_DIR)/");
   for (s = 0; s < config->section_count; s++) {
      split_section *sec = &sections[s];
      switch (sec->type) {
         case TYPE_GEO:
            count += i + strlen(sec->label) + 4;
            break;
         case TYPE_MIO0:
            count += i + strlen(sec->label) + 4;
            break;
         case TYPE_LEVEL:
            level_alloc += j + strlen(sec->label) + 4;
            break;
         default:
            break;
      }
   }

   makeheader_mio0 = malloc(count);
   sprintf(makeheader_mio0, "MIO0_FILES =");

   makeheader_level = malloc(level_alloc);
   sprintf(makeheader_level, "LEVEL_FILES =");

   fmake = fopen(makefile_name, "w");
   fprintf(fmake, "TARGET = %s\n", config->basename);
   fprintf(fmake, "LD_SCRIPT = $(TARGET).ld\n");
   fprintf(fmake, "MIO0_DIR = %s\n", MIO0_SUBDIR);
   fprintf(fmake, "TEXTURE_DIR = %s\n", TEXTURE_SUBDIR);
   fprintf(fmake, "GEO_DIR = %s\n", GEO_SUBDIR);
   fprintf(fmake, "LEVEL_DIR = %s\n\n", LEVEL_SUBDIR);
   fprintf(fmake, "MUSIC_DIR = %s\n\n", MUSIC_SUBDIR);

   fprintf(fasm, "\n.section .mio0\n");
   for (s = 0; s < config->section_count; s++) {
      split_section *sec = &sections[s];
      switch (sec->type) {
         case TYPE_GEO:
         {
            char geofilename[FILENAME_MAX];
            FILE *fgeo;
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(geofilename, "%s.%06X.geo.s", config->basename, sec->start);
               sprintf(start_label, "L%06X", sec->start);
            } else {
               sprintf(geofilename, "%s.geo.s", sec->label);
               strcpy(start_label, sec->label);
            }
            sprintf(outfilename, "%s/%s", GEO_SUBDIR, geofilename);
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);

            // decode and write level data out
            fgeo = fopen(outfilepath, "w");
            if (fgeo == NULL) {
               perror(outfilepath);
               exit(1);
            }
            write_geolayout(fgeo, &data[sec->start], 0, sec->end - sec->start, config);
            fclose(fgeo);

            fprintf(fasm, "\n.align 4, 0x01\n");
            fprintf(fasm, ".global %s\n", start_label);
            fprintf(fasm, "%s:\n", start_label);
            fprintf(fasm, ".include \"%s\"\n", outfilename);
            fprintf(fasm, "%s_end:\n", start_label);
            // append to Makefile
            sprintf(maketmp, " \\\n$(GEO_DIR)/%s", geofilename);
            strcat(makeheader_level, maketmp);
            break;
         }
         case TYPE_MIO0:
         {
            char binfilename[FILENAME_MAX];
            INFO("Section MIO0: %s %X-%X\n", sec->label, sec->start, sec->end);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(outfilename, "%06X.mio0", sec->start);
            } else {
               sprintf(outfilename, "%s.mio0", sec->label);
            }
            sprintf(mio0filename, "%s/%s", mio0_dir, outfilename);
            write_file(mio0filename, &data[sec->start], sec->end - sec->start);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "L%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            fprintf(fasm, "\n.align 4, 0x01\n");
            fprintf(fasm, ".global %s\n", start_label);
            fprintf(fasm, "%s:\n", start_label);
            fprintf(fasm, ".incbin \"%s/%s\"\n", MIO0_SUBDIR, outfilename);
            fprintf(fasm, "%s_end:\n", start_label);
            // append to Makefile
            sprintf(maketmp, " \\\n$(MIO0_DIR)/%s", outfilename);
            strcat(makeheader_mio0, maketmp);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(binfilename, "%s/%06X.bin", mio0_dir, sec->start);
            } else {
               sprintf(binfilename, "%s/%s.bin", mio0_dir, sec->label);
            }

            // extract MIO0 data
            mio0_decode_file(mio0filename, 0, binfilename);

            // extract texture data
            if (sec->extra) {
               texture *texts = sec->extra;
               int t;
               unsigned int offset = 0;
               if (sec->label == NULL || sec->label[0] == '\0') {
                  fprintf(fmake, "$(MIO0_DIR)/%06X.bin:", sec->start);
               } else {
                  fprintf(fmake, "$(MIO0_DIR)/%s.bin: ", sec->label);
               }
               INFO("Extracting textures from %s\n", sec->label);
               for (t = 0; t < sec->extra_len; t++) {
                  w = texts[t].width;
                  h = texts[t].height;
                  offset = texts[t].offset;
                  switch (texts[t].format) {
                     case FORMAT_IA:
                     {
                        ia *img = file2ia(binfilename, offset, w, h, texts[t].depth);
                        if (img) {
                           sprintf(outfilename, "%s.0x%05X.ia%d.png", sec->label, offset, texts[t].depth);
                           sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                           ia2png(img, w, h, outfilepath);
                           free(img);
                           fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                        }
                        break;
                     }
                     case FORMAT_RGBA:
                     {
                        rgba *img = file2rgba(binfilename, offset, w, h);
                        if (img) {
                           sprintf(outfilename, "%s.0x%05X.png", sec->label, offset);
                           sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                           rgba2png(img, w, h, outfilepath);
                           free(img);
                           fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                        }
                        break;
                     }
                     case FORMAT_SKYBOX:
                     {
                        // read in grid of MxN 32x32 tiles and save them as M*31xN*31 image
                        rgba *img;
                        unsigned int sky_offset = offset;
                        int m, n;
                        int tx, ty;
                        m = w/32;
                        n = h/32;
                        img = malloc(w*h*sizeof(rgba));
                        w -= m; // adjust for overlap
                        h -= n;
                        for (ty = 0; ty < n; ty++) {
                           for (tx = 0; tx < m; tx++) {
                              rgba *tile = file2rgba(binfilename, sky_offset, 32, 32);
                              int cx, cy;
                              for (cy = 0; cy < 31; cy++) {
                                 for (cx = 0; cx < 31; cx++) {
                                    int out_off = 31*w*ty + 31*tx + w*cy + cx;
                                    int in_off = 32*cy+cx;
                                    img[out_off] = tile[in_off];
                                 }
                              }
                              free(tile);
                              sky_offset += 32*32*2;
                           }
                        }
                        sprintf(outfilename, "%s.0x%05X.skybox.png", sec->label, offset);
                        sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                        rgba2png(img, w, h, outfilepath);
                        free(img);
                        fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                        break;
                     }
                     case FORMAT_COLLISION:
                     {
                        sprintf(outfilename, "%s.0x%05X.collision.obj", sec->label, offset);
                        sprintf(outfilepath, "%s/%s", model_dir, outfilename);
                        INFO("Generating collision model %s\n", outfilename);
                        collision2obj(binfilename, offset, outfilepath, sec->label, args->scale);
                        break;
                     }
                     default:
                        ERROR("Don't know what to do with format %d\n", texts[t].format);
                        exit(1);
                  }
               }
               fprintf(fmake, "\n\t$(N64GRAPHICS) $@ $^\n\n");
            }
            if (args->large_texture) {
               INFO("Generating large texture for %s\n", sec->label);
               w = 32;
               h = filesize(binfilename) / (w * 2);
               rgba *img = file2rgba(binfilename, 0, w, h);
               if (img) {
                  sprintf(outfilename, "%s.ALL.png", sec->label);
                  sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                  rgba2png(img, w, h, outfilepath);
                  free(img);
                  fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                  img = NULL;
               }
            }
            // touch bin, then mio0 files so 'make' doesn't rebuild them right away
            touch_file(binfilename);
            touch_file(mio0filename);
            break;
         }
         case TYPE_LEVEL:
         {
            FILE *flevel;
            char levelfilename[FILENAME_MAX];
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "L%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            INFO("Section relocated level: %s %X-%X\n", start_label, sec->start, sec->end);
            sprintf(levelfilename, "%s.s", start_label);
            sprintf(outfilename, "%s/%s", LEVEL_SUBDIR, levelfilename);
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);

            // decode and write level data out
            flevel = fopen(outfilepath, "w");
            if (flevel == NULL) {
               perror(outfilepath);
               exit(1);
            }
            fprintf(flevel, "# level script %s from %X-%X\n\n", start_label, sec->start, sec->end);
            fprintf(flevel, ".section .mio0\n\n");
            fprintf(flevel, ".global %s\n", start_label);
            fprintf(flevel, ".align 4, 0x01\n");
            fprintf(flevel, "%s:\n", start_label);
            write_level(flevel, data, config, s);
            fprintf(flevel, "%s_end:\n", start_label);
            fclose(flevel);

            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "L%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            fprintf(fasm, "\n.include \"%s\"\n", outfilename);
            // append to Makefile
            sprintf(maketmp, " \\\n$(LEVEL_DIR)/%s", levelfilename);
            strcat(makeheader_level, maketmp);
            break;
         }
         case TYPE_BEHAVIOR:
         {
            FILE *f_beh;
            char beh_filename[FILENAME_MAX];
            INFO("Section relocated behavior: %s %X-%X\n", sec->label, sec->start, sec->end);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(beh_filename, "%06X.s", sec->start);
            } else {
               sprintf(beh_filename, "%s.s", sec->label);
            }
            sprintf(outfilename, "%s/%s", BEHAVIOR_SUBDIR, beh_filename);
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);
            // decode and write level data out
            f_beh = fopen(outfilepath, "w");
            if (f_beh == NULL) {
               perror(outfilepath);
               exit(1);
            }
            write_behavior(f_beh, data, config, s);
            fclose(f_beh);

            fprintf(fasm, "\n.section .behavior, \"a\"\n");
            fprintf(fasm, "\n.global %s\n", sec->label);
            fprintf(fasm, ".global %s_end\n", sec->label);
            fprintf(fasm, "%s:\n", sec->label);
            fprintf(fasm, ".include \"%s\"\n", outfilename);
            fprintf(fasm, "%s_end:\n", sec->label);
            fprintf(fasm, "\n\n.section .mio0\n");

            // append to Makefile
            sprintf(maketmp, " \\\n%s/%s", BEHAVIOR_SUBDIR, beh_filename);
            strcat(makeheader_level, maketmp);
            break;
         }
         default:
            break;
      }
   }
   fprintf(fmake, "\n\n%s", makeheader_mio0);
   fprintf(fmake, "\n\n%s", makeheader_level);
   fprintf(fmake, "\n\n%s", makeheader_music);

   // dump the proc table
   if (args->gen_proc_table)
   {
      unsigned int ram_address;
      unsigned int rom_offset;
      int i, j;
      printf("static const procedure proc_table[] = {\n");
      for (i = 0; i < config->label_count; i++) {
         ram_address = config->labels[i].ram_addr;
         rom_offset = ram_to_rom(config, ram_address);
         for (j = 0; j < procs->count; j++) {
            procedure *p = &procs->procedures[j];
            if (p->start == ram_address) {
            printf("   {0x%08X, 0x%08X, 0x%06X, 0x%06X, \"%s\"},\n",
                   p->start, p->end, rom_offset, ram_to_rom(config, p->end),
                   config->labels[i].name);
               break;
            }
         }
      }
      printf("};\n");
   }

   // cleanup
   free(makeheader_mio0);
   free(makeheader_level);
   free(makeheader_music);
   fclose(fmake);
   fclose(fasm);

   // output top-level makefile
   sprintf(makefile_name, "%s/Makefile", args->output_dir);
   fmake = fopen(makefile_name, "w");
   fprintf(fmake, makefile_data);
   fclose(fmake);

   generate_ld_script(args, config);
}

static void print_usage(void)
{
   ERROR("Usage: n64split [-c CONFIG] [-o OUTPUT_DIR] [-s SCALE] [-t] [-v] ROM\n"
         "\n"
         "n64split v" N64SPLIT_VERSION ": N64 ROM splitter, texture ripper, recursive disassembler\n"
         "\n"
         "Optional arguments:\n"
         " -c CONFIG     ROM configuration file (default: determine from checksum)\n"
         " -o OUTPUT_DIR output directory (default: {CONFIG.basename}.split)\n"
         " -s SCALE      amount to scale models by (default: %f)\n"
         " -p            generate procedure table for analysis\n"
         " -t            generate large texture for MIO0 blocks\n"
         " -v            verbose progress output\n"
         "\n"
         "File arguments:\n"
         " ROM        input ROM file\n",
         default_args.scale);
   exit(1);
}

// parse command line arguments
static void parse_arguments(int argc, char *argv[], arg_config *config)
{
   int i;
   int file_count = 0;
   if (argc < 2) {
      print_usage();
      exit(1);
   }
   for (i = 1; i < argc; i++) {
      if (argv[i][0] == '-') {
         switch (argv[i][1]) {
            case 'c':
               if (++i >= argc) {
                  print_usage();
               }
               strcpy(config->config_file, argv[i]);
               break;
            case 'o':
               if (++i >= argc) {
                  print_usage();
               }
               strcpy(config->output_dir, argv[i]);
               break;
            case 'p':
               config->gen_proc_table = 1;
               break;
            case 's':
               if (++i >= argc) {
                  print_usage();
               }
               config->scale = strtof(argv[i], NULL);
               break;
            case 't':
               config->large_texture = 1;
               break;
            case 'v':
               g_verbosity = 1;
               break;
            default:
               print_usage();
               break;
         }
      } else {
         if (file_count == 0) {
            strcpy(config->input_file, argv[i]);
         } else {
            // too many
            print_usage();
         }
         file_count++;
      }
   }
   if (file_count < 1) {
      print_usage();
   }
}

static int detect_config_file(unsigned int c1, unsigned int c2, rom_config *config)
{
#define CONFIGS_DIR "configs"
   dir_list list;
   int config_ret;
   int ret_val = 0;
   int i;

   dir_list_ext(CONFIGS_DIR, ".config", &list);

   for (i = 0; i < list.count; i++) {
      config_ret = parse_config_file(list.files[i], config);
      INFO("Checking config file '%s' (%X, %X)\n", list.files[i], config->checksum1, config->checksum2);
      if (config_ret == 0 && c1 == config->checksum1 && c2 == config->checksum2) {
         ERROR("Using config file: %s\n", list.files[i]);
         ret_val = 1;
         break;
      }
   }

   dir_list_free(&list);

   return ret_val;
}

int main(int argc, char *argv[])
{
   arg_config args;
   rom_config config;
   proc_table procs;
   long len;
   unsigned char *data;
   int ret_val;
   unsigned int size;
   unsigned int asm_size;
   float percent;
   int i;
   n64_rom_format rom_type;

   memset(&procs, 0, sizeof(procs));
   procs.count = 0;

   args = default_args;
   parse_arguments(argc, argv, &args);

   len = read_file(args.input_file, &data);

   if (len <= 0) {
      return 2;
   }

   // confirm valid N64 ROM
   rom_type = n64_rom_type(data, len);
   switch (rom_type) {
      case N64_ROM_Z64:
         break; // Z64 is expected format
      case N64_ROM_V64:
         // byte-swapped BADC format, swap to big-endian ABCD format for processing
         INFO("Byte-swapping ROM\n");
         swap_bytes(data, len);
         break;
      case N64_ROM_INVALID:
         ERROR("This does not appear to be a valid N64 ROM\n");
         exit(1);
         break;
   }

   // if no config file supplied, find the right one
   if (0 == strcmp(args.config_file, "")) {
      ret_val = detect_config_file(read_u32_be(data+0x10), read_u32_be(data+0x14), &config);
      if (!ret_val) {
         ERROR("Error: could not find valid config file for '%s'\n", args.input_file);
         return 1;
      }
   } else {
      ret_val = parse_config_file(args.config_file, &config);
      if (ret_val != 0) {
         return 1;
      }
   }

   if (validate_config(&config, len)) {
      return 3;
   }

   // if no output directory specified, construct one from config file
   if (0 == strcmp(args.output_dir, "")) {
      sprintf(args.output_dir, "%s.split", config.basename);
      printf("Splitting into \"%s\" directory\n", args.output_dir);
   }

   // fill procs table from config labels
   mipsdisasm_add_procs(&procs, &config, len);

   // first pass disassembler
   INFO("Running first pass disassembler...\n");
   mipsdisasm_pass1(data, len, &procs, &config);

   // split the ROM
   INFO("Splitting ROM...\n");
   split_file(data, len, &procs, &args, &config);

   // print some stats
   printf("\nROM split statistics:\n");
   size = 0;
   asm_size = 0;
   for (i = 0; i < config.section_count; i++) {
      if (config.sections[i].type != TYPE_BIN) {
         size += config.sections[i].end - config.sections[i].start;
      }
      if (config.sections[i].type == TYPE_ASM) {
         asm_size += config.sections[i].end - config.sections[i].start;
      }
   }
   percent = (float)(100 * size) / (float)(len);
   printf("Total decoded section size:  %X/%lX (%.2f%%)\n", size, len, percent);
   size = 0;
   for (i = 0; i < procs.count; i++) {
      size += procs.procedures[i].end - procs.procedures[i].start;
   }
   percent = (float)(100 * size) / (float)(asm_size);
   printf("Total disassembled ASM size: %X/%X (%.2f%%)\n", size, asm_size, percent);

   return 0;
}
