#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>

#include <zlib.h>

#include "config.h"
#include "libblast.h"
#include "libmio0.h"
#include "libsfx.h"
#include "mipsdisasm.h"
#include "n64graphics.h"
#include "strutils.h"
#include "utils.h"

#define N64SPLIT_VERSION "0.4a"

#define GLOBALS_FILE "globals.inc"
#define MACROS_FILE "macros.inc"
#define MUSIC_SUBDIR    "music"

#define BIN_SUBDIR      "bin"
#define ASM_SUBDIR      "asm"
#define MIO0_SUBDIR     "bin"
#define TEXTURE_SUBDIR  "textures"
#define GEO_SUBDIR      "geo"
#define LEVEL_SUBDIR    "levels"
#define MODEL_SUBDIR    "models"
#define BEHAVIOR_SUBDIR "."

typedef struct _arg_config
{
   char input_file[FILENAME_MAX];
   char config_file[FILENAME_MAX];
   char output_dir[FILENAME_MAX];
   float model_scale;
   bool raw_texture; // TODO: this should be the default path once n64graphics is updated
   bool large_texture;
   bool large_texture_depth;
   bool keep_going;
   bool merge_pseudo;
} arg_config;

typedef enum {
   N64_ROM_INVALID,
   N64_ROM_Z64,
   N64_ROM_V64,
} n64_rom_format;

// default configuration
static const arg_config default_args = 
{
   .input_file = "",
   .config_file = "",
   .output_dir = "",
   .model_scale = 1024.0f,
   .raw_texture = false,
   .large_texture = false,
   .large_texture_depth = 16,
   .keep_going = false,
   .merge_pseudo = false,
};

// static files
#include "n64split.makefile.h"
#include "n64split.collision.mtl.h"

const char asm_header[] = 
   "# %s disassembly and split file\n"
   "# generated by n64split v%s - N64 ROM splitter\n"
   "\n"
   "# assembler directives\n"
   ".set noat      # allow manual use of $at\n"
   ".set noreorder # don't insert nops after branches\n"
   "\n"
   ".include \"" GLOBALS_FILE "\"\n"
   "\n";



static n64_rom_format n64_rom_type(unsigned char *buf, unsigned int length)
{
   const unsigned char bs[] = {0x37, 0x80, 0x40, 0x12}; // byte-swapped
   const unsigned char be[] = {0x80, 0x37, 0x12, 0x40}; // big-endian
   if (length >= (8 * MB)) {
      if (!memcmp(buf, bs, sizeof(bs))) {
         return N64_ROM_V64;
      }
      if (!memcmp(buf, be, sizeof(be))) {
         return N64_ROM_Z64;
      }
   }
   return N64_ROM_INVALID;
}

static void gzip_decode_file(char *gzfilename, int offset, char *binfilename)
{
#define CHUNK 0x4000
   FILE *file;
   FILE *fout;
   z_stream strm = {0};
   unsigned char in[CHUNK];
   unsigned char out[CHUNK];

   // TODO: add some error checking
   strm.zalloc = Z_NULL;
   strm.zfree = Z_NULL;
   strm.opaque = Z_NULL;
   strm.avail_in = 0;
   inflateInit2(&strm, 16+MAX_WBITS);

   file = fopen(gzfilename, "rb");
   fout = fopen(binfilename, "wb");
   fseek(file, offset, SEEK_SET);
   while (1) {
      int bytes_read;
      bytes_read = fread(in, sizeof(char), sizeof(in), file);
      strm.avail_in = bytes_read;
      strm.next_in = in;
      do {
         strm.avail_out = CHUNK;
         strm.next_out = out;
         inflate(&strm, Z_NO_FLUSH);
         fwrite(out, sizeof(char), CHUNK - strm.avail_out, fout);
      } while (strm.avail_out == 0);
      if (feof(file)) {
         inflateEnd(&strm);
         break;
      }
   }
   fclose(file);
   fclose(fout);
}

static int config_section_lookup(rom_config *config, unsigned int addr, char *label, int is_end)
{
   int i;
   // check for ROM offsets
   switch (is_end) {
      case 0:
         for (i = 0; i < config->section_count; i++) {
            // TODO: hack until mario_animation gets moved or AT() is used
            if (config->sections[i].start == addr && addr != 0x4EC000) {
               if (config->sections[i].label[0] != '\0') {
                  sprintf(label, "%s", config->sections[i].label);
               } else {
                  sprintf(label, "%s_%06X", config_section2str(config->sections[i].type), addr);
               }
               INFO("Found 0 %06X: %s\n", addr, label);
               return 0;
            }
         }
         break;
      case 1:
         for (i = 0; i < config->section_count; i++) {
            if (config->sections[i].end == addr) {
               if (config->sections[i].label[0] != '\0') {
                  sprintf(label, "%s_end", config->sections[i].label);
               } else {
                  sprintf(label, "%s_%06X", config_section2str(config->sections[i].type), addr);
               }
               INFO("Found 1 %06X: %s\n", addr, label);
               return 0;
            }
         }
         break;
      default:
         break;
   }
   sprintf(label, "0x%X", addr);
   return -1;
}

static void write_level(FILE *out, unsigned char *data, rom_config *config, int s, disasm_state *state)
{
   char start_label[128];
   char end_label[128];
   char dst_label[128];
   split_section *sec;
   unsigned int ptr_start;
   unsigned int ptr_end;
   unsigned int dst;
   unsigned int a;
   int i;
   int beh_i;

   sec = &config->sections[s];

   beh_i = -1;
   // see if there is a behavior section
   for (i = 0; i < config->section_count; i++) {
      if (config->sections[i].type == TYPE_SM64_BEHAVIOR) {
         beh_i = i;
         break;
      }
   }
   a = sec->start;
   while (a < sec->end) {
      // length = 0 ends level script
      if (data[a+1] == 0) {
         break;
      }
      switch (data[a]) {
         case 0x00: // load and jump from ROM into a RAM segment
         case 0x01: // load and jump from ROM into a RAM segment
         case 0x17: // copy uncompressed data from ROM to a RAM segment
         case 0x18: // decompress MIO0 data from ROM and copy it into a RAM segment
         case 0x1A: // decompress MIO0 data from ROM and copy it into a RAM segment (for texture only segments?)
            ptr_start = read_u32_be(&data[a+4]);
            ptr_end = read_u32_be(&data[a+8]);
            config_section_lookup(config, ptr_start, start_label, 0);
            config_section_lookup(config,   ptr_end,   end_label, 1);
            fprintf(out, ".word 0x");
            for (i = 0; i < 4; i++) {
               fprintf(out, "%02X", data[a+i]);
            }
            if (0 == strcmp("behavior_data", start_label)) {
               fprintf(out, ", __load_%s, __load_%s", start_label, end_label);
            } else {
               fprintf(out, ", %s, %s", start_label, end_label);
            }
            for (i = 12; i < data[a+1]; i++) {
               if ((i & 0x3) == 0) {
                  fprintf(out, ", 0x");
               }
               fprintf(out, "%02X", data[a+i]);
            }
            fprintf(out, "\n");
            break;
         case 0x11: // call function
         case 0x12: // call function
            ptr_start = read_u32_be(&data[a+0x4]);
            disasm_label_lookup(state, ptr_start, start_label);
            fprintf(out, ".word 0x%08X, %s # %08X\n", read_u32_be(&data[a]), start_label, ptr_start);
            break;
         case 0x16: // load ASM into RAM
            dst       = read_u32_be(&data[a+0x4]);
            ptr_start = read_u32_be(&data[a+0x8]);
            ptr_end   = read_u32_be(&data[a+0xc]);
            // TODO: differentiate between start/end
            disasm_label_lookup(state, dst, dst_label);
            config_section_lookup(config, ptr_start, start_label, 0);
            config_section_lookup(config, ptr_end, end_label, 1);
            fprintf(out, ".word 0x");
            for (i = 0; i < 4; i++) {
               fprintf(out, "%02X", data[a+i]);
            }
            fprintf(out, ", %s, %s, %s\n", dst_label, start_label, end_label);
            break;
         case 0x25: // load mario object with behavior
         case 0x24: // load object with behavior
            fprintf(out, ".word 0x%08X", read_u32_be(&data[a]));
            for (i = 4; i < data[a+1]-4; i+=4) {
               fprintf(out, ", 0x%08X", read_u32_be(&data[a+i]));
            }
            dst = read_u32_be(&data[a+i]);
            if (beh_i >= 0) {
               unsigned int offset = dst & 0xFFFFFF;
               split_section *beh = config->sections[beh_i].children;
               for (i = 0; i < config->sections[beh_i].child_count; i++) {
                  if (offset == beh[i].start) {
                     fprintf(out, ", %s", beh[i].label);
                     break;
                  }
               }
               if (i >= config->sections[beh_i].child_count) {
                  ERROR("Error: cannot find behavior %04X needed at offset %X\n", offset, a);
               }
            } else {
               fprintf(out, ", 0x%08X", dst);
            }
            fprintf(out, "\n");
            break;
         default:
            fprintf(out, ".word 0x%08X", read_u32_be(&data[a]));
            for (i = 4; i < data[a+1]; i+=4) {
               fprintf(out, ", 0x%08X", read_u32_be(&data[a+i]));
            }
            fprintf(out, "\n");
            break;
      }
      a += data[a+1];
   }
   // align to next 16-byte boundary
   if (a & 0x0F) {
      fprintf(out, "# begin %s alignment 0x%X\n", sec->label, a);
      fprintf(out, ".byte ");
      fprint_hex_source(out, &data[a], ALIGN(a, 16) - a);
      fprintf(out, "\n");
      a = ALIGN(a, 16);
   }
   // remaining is geo layout script
   fprintf(out, "# begin %s geo 0x%X\n", sec->label, a);
   write_geolayout(out, &data[sec->start], a - sec->start, sec->end - sec->start, state);
}

static void generate_globals(arg_config *args, rom_config *config)
{
   char globalfilename[FILENAME_MAX];
   FILE *fglobal;
   sprintf(globalfilename, "%s/%s", args->output_dir, GLOBALS_FILE);
   fglobal = fopen(globalfilename, "w");
   if (fglobal == NULL) {
      ERROR("Error opening %s\n", globalfilename);
      exit(3);
   }
   fprintf(fglobal, "# globally accessible functions and data\n"
                    "# these will be accessible by C code and show up in the .map file\n\n");
   for (int i = 0; i < config->label_count; i++) {
      fprintf(fglobal, ".global %s\n", config->labels[i].name);
   }
   fprintf(fglobal, "\n");

   fclose(fglobal);
}

static void generate_macros(arg_config *args)
{
   char incfilename[FILENAME_MAX];
   FILE *finc;
   sprintf(incfilename, "%s/%s", args->output_dir, MACROS_FILE);
   finc = fopen(incfilename, "w");
   if (finc == NULL) {
      ERROR("Error opening %s\n", incfilename);
      exit(3);
   }
   fprintf(finc, "# common macros\n"
                 "\n"
                 "# F3D vertex\n"
                 ".macro vertex \\x, \\y, \\z, \\u, \\v, \\r=0xFF, \\g=0xFF, \\b=0xFF, \\a=0xFF\n"
                 "   .hword \\x, \\y, \\z, 0, \\u, \\v\n   .byte \\r, \\g, \\b, \\a\n"
                 ".endm\n");
   fclose(finc);
}


static void generate_ld_script(arg_config *args, rom_config *config)
{
   char ldfilename[FILENAME_MAX];
   FILE *fld;
   sprintf(ldfilename, "%s/%s.ld", args->output_dir, config->basename);
   fld = fopen(ldfilename, "w");
   if (fld == NULL) {
      ERROR("Error opening %s\n", ldfilename);
      exit(3);
   }
   fprintf(fld,
"/* %s linker script\n"
" * generated by n64split v%s - N64 ROM splitter */\n"
"\n"
"OUTPUT_FORMAT (\"elf32-bigmips\", \"elf32-bigmips\", \"elf32-littlemips\")\n"
"OUTPUT_ARCH (mips)\n"
"\n"
"SECTIONS\n"
"{\n"
"   /* header and boot */\n"
"   .header 0x0 : AT(0x0) {\n"
"      * (.header);\n"
"      * (.boot);\n"
"   }\n"
"\n"
"   /* load MIO0 and level data at 0x800000 */\n"
"   .rodata 0x800000 : {\n"
"      FILL (0x01) /* fill unused with 0x01 */\n"
"      * (.mio0);\n"
"      * (.rodata);\n"
"      * (.data);\n"
"      * (.MIPS.abiflags);\n"
"      . = ALIGN(0x10);\n"
"   }\n"
"\n"
"   /* use segmented addressing for behaviors */\n"
"   .behavior 0x13000000 : AT( LOADADDR(.rodata) + SIZEOF(.rodata) ) {\n"
"      FILL (0x01) /* fill unused with 0x01 */\n"
"      * (.behavior);\n"
"      behavior_length = . - 0x13000000;\n"
"      /* default 4MB data (12MB ROM) */\n"
"      . = 0x400000 - SIZEOF(.rodata);\n"
"   }\n"
"   __load_behavior_data = LOADADDR(.behavior);\n"
"   __load_behavior_data_end = LOADADDR(.behavior) + behavior_length;\n"
"\n", config->name, N64SPLIT_VERSION);
   for (int i = 0; i < config->section_count; i++) {
      split_section *s = &config->sections[i];
      if (s->type == TYPE_ASM) {
         unsigned int rom_start = s->start;
         unsigned int rom_end = s->end;
         unsigned int ram_start = s->vaddr;
         unsigned int length = rom_end - rom_start;
         fprintf(fld,
"   /* 0x%08X %06X-%06X [%X] */\n"
"   .text%08X 0x%08X : AT(0x%06X) {\n"
"      * (.text%08X);\n"
"   }\n"
"\n", ram_start, rom_start, rom_end, length,
      ram_start, ram_start, rom_start, ram_start);
      }
   }
   fprintf(fld, "}\n");

   fclose(fld);
}

void section_sm64_geo(unsigned char *data, arg_config *args, rom_config *config, disasm_state *state, split_section *sec, char* start_label, char* outfilename, char* outfilepath, FILE *fasm, strbuf *makeheader_level) {
   char geofilename[FILENAME_MAX];
   FILE *fgeo;
   if (sec->label == NULL || sec->label[0] == '\0') {
      sprintf(geofilename, "%s.%06X.geo.s", config->basename, sec->start);
      sprintf(start_label, "L%06X", sec->start);
   } else {
      sprintf(geofilename, "%s.geo.s", sec->label);
      strcpy(start_label, sec->label);
   }
   sprintf(outfilename, "%s/%s", GEO_SUBDIR, geofilename);
   sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);

   // decode and write level data out
   fgeo = fopen(outfilepath, "w");
   if (fgeo == NULL) {
      perror(outfilepath);
      exit(1);
   }
   write_geolayout(fgeo, &data[sec->start], 0, sec->end - sec->start, state);
   fclose(fgeo);

   fprintf(fasm, "\n.align 4, 0x01\n");
   fprintf(fasm, ".global %s\n", start_label);
   fprintf(fasm, "%s:\n", start_label);
   fprintf(fasm, ".include \"%s\"\n", outfilename);
   fprintf(fasm, "%s_end:\n", start_label);
   // append to Makefile
   strbuf_sprintf(&makeheader_level, " \\\n$(GEO_DIR)/%s", geofilename);
}

void write_bin_type(split_section *sec, char* outfilename, char* start_label, FILE* fasm, unsigned char *data, char* outfilepath, arg_config * args, rom_config *config) {
   char* output_dir=BIN_SUBDIR;
   char bin_dir[FILENAME_MAX];
   if (sec->section_name != NULL) {
      output_dir=sec->section_name;
   }
   sprintf(bin_dir, "%s/%s", args->output_dir, output_dir);
   make_dir(bin_dir);

   if (sec->label == NULL || sec->label[0] == '\0') {
      sprintf(outfilename, "%s/%s.%06X.%s", output_dir, config->basename, sec->start,sec->section_name);
   } else {
      sprintf(outfilename, "%s/%s.%06X.%s.%s", output_dir, config->basename, sec->start, sec->label,sec->section_name);
   }
   sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);
   write_file(outfilepath, &data[sec->start], sec->end - sec->start);
   if (sec->label == NULL || sec->label[0] == '\0') {
      sprintf(start_label, "L%06X", sec->start);
   } else {
      strcpy(start_label, sec->label);
   }
   fprintf(fasm, "%s:\n", start_label);
   fprintf(fasm, ".incbin \"%s\"\n", outfilename);
   fprintf(fasm, "%s_end:\n", start_label);
}

static void split_file(unsigned char *data, unsigned int length, arg_config *args, rom_config *config, disasm_state *state)
{

   char makefile_name[FILENAME_MAX];
   char bin_dir[FILENAME_MAX];
   char asm_dir[FILENAME_MAX];
   char mio0_dir[FILENAME_MAX];
   char texture_dir[FILENAME_MAX];
   char geo_dir[FILENAME_MAX];
   char level_dir[FILENAME_MAX];
   char model_dir[FILENAME_MAX];
   char behavior_dir[FILENAME_MAX];
   char asmfilename[FILENAME_MAX];
   char outfilename[FILENAME_MAX];
   char outfilepath[FILENAME_MAX];
   char mio0filename[FILENAME_MAX];
   char start_label[256];
   strbuf makeheader_mio0;
   strbuf makeheader_level;
   strbuf makeheader_music;
   FILE *fasm;
   FILE *fmake;
   int s;
   int i;
   unsigned int a;
   unsigned int w, h;
   unsigned int prev_end = 0;
   unsigned int ptr;
   split_section *sections = config->sections;

   // create directories
   sprintf(makefile_name, "%s/Makefile.split", args->output_dir);
   sprintf(bin_dir, "%s/%s", args->output_dir, BIN_SUBDIR);
   sprintf(asm_dir, "%s/%s", args->output_dir, ASM_SUBDIR);
   sprintf(mio0_dir, "%s/%s", args->output_dir, MIO0_SUBDIR);
   sprintf(texture_dir, "%s/%s", args->output_dir, TEXTURE_SUBDIR);
   sprintf(geo_dir, "%s/%s", args->output_dir, GEO_SUBDIR);
   sprintf(level_dir, "%s/%s", args->output_dir, LEVEL_SUBDIR);
   sprintf(model_dir, "%s/%s", args->output_dir, MODEL_SUBDIR);
   sprintf(behavior_dir, "%s/%s", args->output_dir, BEHAVIOR_SUBDIR);
   make_dir(args->output_dir);
   make_dir(bin_dir);
   make_dir(asm_dir);
   make_dir(mio0_dir);
   make_dir(texture_dir);
   make_dir(geo_dir);
   make_dir(level_dir);
   make_dir(model_dir);
   make_dir(behavior_dir);

   // open main assembly file and write header
   sprintf(asmfilename, "%s/%s.s", args->output_dir, config->basename);
   fasm = fopen(asmfilename, "w");
   if (fasm == NULL) {
      ERROR("Error opening %s\n", asmfilename);
      exit(3);
   }
   fprintf(fasm, asm_header, config->name, N64SPLIT_VERSION);

   // generate globals include file
   generate_globals(args, config);
   // generate common macros
   generate_macros(args);

   strbuf_alloc(&makeheader_music, 256);
   strbuf_sprintf(&makeheader_music, "MUSIC_FILES =");

   //Need both sfx sections to parse
   split_section *sfxSec = NULL;
   
   for (s = 0; s < config->section_count; s++) {
      split_section *sec = &sections[s];

      // error checking
      if (sec->start >= length || sec->end > length) {
         ERROR("Error: section past end: 0x%X, 0x%X (%s) > 0x%X\n",
               sec->start, sec->end, sec->label ? sec->label : "", length);
         exit(4);
      }

      // fill gaps between regions
      if (sec->start != prev_end) {
         int gap_len = sec->start - prev_end;
         INFO("Filling gap before region %d (%d bytes)\n", s, gap_len);
         fprintf(fasm, "# Unknown region %06X-%06X [%X]\n", prev_end, sec->start, gap_len);
         // for small gaps, just output bytes
         if (gap_len <= 0x80) {
            unsigned int group_offset = prev_end;
            while (gap_len > 0) {
               int group_len = MIN(gap_len, 0x10);
               fprintf(fasm, ".byte ");
               fprint_hex_source(fasm, &data[group_offset], group_len);
               fprintf(fasm, "\n");
               gap_len -= group_len;
               group_offset += group_len;
            }
         } else {
            // TODO move gap fillers into a different subdirectory
            sprintf(outfilename, "%s/%s.%06X.bin", BIN_SUBDIR, config->basename, prev_end);
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);
            write_file(outfilepath, &data[prev_end], gap_len);
            fprintf(fasm, ".incbin \"%s\"\n", outfilename);
         }
         fprintf(fasm, "\n");
      }

      switch (sec->type)
      {
         case TYPE_HEADER:
            INFO("Section header: %X-%X\n", sec->start, sec->end);
            fprintf(fasm, ".section .header, \"a\"\n"
                          ".byte  0x%02X", data[sec->start]);
            for (i = 1; i < 4; i++) {
               fprintf(fasm, ", 0x%02X", data[sec->start + i]);
            }
            fprintf(fasm, " # PI BSD Domain 1 register\n");
            fprintf(fasm, ".word  0x%08X # clock rate setting\n", read_u32_be(&data[sec->start + 0x4]));
            fprintf(fasm, ".word  0x%08X # entry point\n", read_u32_be(&data[sec->start + 0x8]));
            fprintf(fasm, ".word  0x%08X # release\n", read_u32_be(&data[sec->start + 0xc]));
            fprintf(fasm, ".word  0x%08X # checksum1\n", read_u32_be(&data[sec->start + 0x10]));
            fprintf(fasm, ".word  0x%08X # checksum2\n", read_u32_be(&data[sec->start + 0x14]));
            fprintf(fasm, ".word  0x%08X # unknown\n", read_u32_be(&data[sec->start + 0x18]));
            fprintf(fasm, ".word  0x%08X # unknown\n", read_u32_be(&data[sec->start + 0x1C]));
            fprintf(fasm, ".ascii \"");
            fwrite(&data[sec->start + 0x20], 1, 20, fasm);
            fprintf(fasm, "\" # ROM name: 20 bytes\n");
            fprintf(fasm, ".word  0x%08X # unknown\n", read_u32_be(&data[sec->start + 0x34]));
            fprintf(fasm, ".word  0x%08X # cartridge\n", read_u32_be(&data[sec->start + 0x38]));
            fprintf(fasm, ".ascii \"");
            fwrite(&data[sec->start + 0x3C], 1, 2, fasm);
            fprintf(fasm, "\"       # cartridge ID\n");
            fprintf(fasm, ".ascii \"");
            fwrite(&data[sec->start + 0x3E], 1, 1, fasm);
            fprintf(fasm, "\"        # country\n");
            fprintf(fasm, ".byte  0x%02X       # version\n\n", data[sec->start + 0x3F]);
            break;
         case TYPE_BIN:
            write_bin_type(sec, outfilename, start_label, fasm, data, outfilepath, args, config);
            break;
         case TYPE_BLAST:
         case TYPE_MIO0:
         case TYPE_GZIP:
         case TYPE_SM64_GEO:
            // fill previous geometry and MIO0 blocks
            fprintf(fasm, ".space 0x%05x, 0x01 # %s\n", sec->end - sec->start, sec->label);
            break;
         case TYPE_PTR:
            INFO("Section ptr: %X-%X\n", sec->start, sec->end);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "Ptr%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            fprintf(fasm, "%s:\n", start_label);
            for (a = sec->start; a < sec->end; a += 4) {
               ptr = read_u32_be(&data[a]);
               disasm_label_lookup(state, ptr, start_label);
               fprintf(fasm, ".word %s", start_label);
               if (sec->child_count > 0) {
                  for (i = 1; i < sec->child_count; i++) {
                     a += 4;
                     ptr = read_u32_be(&data[a]);
                     disasm_label_lookup(state, ptr, start_label);
                     fprintf(fasm, ", %s", start_label);
                  }
               }
               fprintf(fasm, "\n");
            }
            fprintf(fasm, "\n");
            break;
         case TYPE_ASM:
            INFO("Section asm: %X-%X\n", sec->start, sec->end);
            char section_asmfilename[FILENAME_MAX];
            sprintf(section_asmfilename, "%s/asm/%s.s", args->output_dir, sec->label);
            // Include in main .s file
            fprintf(fasm, ".include \"asm/%s.s\" \n", sec->label);

            // Open seperate .s file for this section
            FILE *section_fasm = fopen(section_asmfilename, "w");
            fprintf(section_fasm, "\n.section .text%08X, \"ax\"\n\n", sec->vaddr);
            mipsdisasm_pass2(section_fasm, state, sec->start);
            fclose(section_fasm);
            break;
         case TYPE_SM64_LEVEL:
            // relocate level scripts to .mio0 area
            // TODO: these shouldn't need to be relocated if load offset can be computed
            fprintf(fasm, ".space 0x%05x, 0x01 # %s\n", sec->end - sec->start, sec->label);
            break;
         case TYPE_SM64_BEHAVIOR:
            // behaviors are done below
            fprintf(fasm, ".space 0x%05x, 0x01 # %s\n", sec->end - sec->start, sec->label);
            break;
         case TYPE_M64:
            parse_music_sequences(fasm, data, sec, args, &makeheader_music);
            break;
         case TYPE_SFX_CTL:
            if (sfxSec == NULL)
               sfxSec = sec;
            else
               parse_sound_banks(fasm, data, sec, sfxSec, args, &makeheader_music); //Fix header later
            break;
         case TYPE_SFX_TBL:
            if (sfxSec == NULL)
               sfxSec = sec;
            else
               parse_sound_banks(fasm, data, sfxSec, sec, args, &makeheader_music); //Fix header later
            break;
         case TYPE_INSTRUMENT_SET:
            parse_instrument_set(fasm, data, sec);
            break;
         default:
            // printf("Treating custom file format as binary %s %s %s\n", sec->section_name, outfilepath, outfilename);
            // ERROR("Don't know what to do with type %d\n", sec->type);
            write_bin_type(sec, outfilename, start_label, fasm, data, outfilepath, args, config);
            break;
      }
      prev_end = sec->end;
   }

   strbuf_alloc(&makeheader_mio0, 1024);
   strbuf_sprintf(&makeheader_mio0, "MIO0_FILES =");

   strbuf_alloc(&makeheader_level, 1024);
   strbuf_sprintf(&makeheader_level, "LEVEL_FILES =");

   fmake = fopen(makefile_name, "w");
   fprintf(fmake, "TARGET = %s\n", config->basename);
   fprintf(fmake, "LD_SCRIPT = $(TARGET).ld\n");
   fprintf(fmake, "MIO0_DIR = %s\n", MIO0_SUBDIR);
   fprintf(fmake, "TEXTURE_DIR = %s\n", TEXTURE_SUBDIR);
   fprintf(fmake, "GEO_DIR = %s\n", GEO_SUBDIR);
   fprintf(fmake, "LEVEL_DIR = %s\n\n", LEVEL_SUBDIR);
   fprintf(fmake, "MUSIC_DIR = %s\n\n", MUSIC_SUBDIR);

   fprintf(fasm, "\n.section .mio0\n");
   for (s = 0; s < config->section_count; s++) {
      split_section *sec = &sections[s];
      switch (sec->type) {
         case TYPE_SM64_GEO:
         {
            section_sm64_geo(data, args, config, state, sec, start_label, outfilename, outfilepath, fasm, &makeheader_level);
            break;
         }
         case TYPE_BLAST:
         case TYPE_GZIP:
         case TYPE_MIO0:
         {
            char binfilename[FILENAME_MAX];
            char extension[8] = {0};
            unsigned char *lut;
            char binasmfilename[FILENAME_MAX];
            FILE *binasm;
            unsigned char *binfilecontents = NULL;
            long binfilelen = 0;
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "L%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            sprintf(binfilename, "%s.s", start_label);
            sprintf(binasmfilename, "%s/%s", bin_dir, binfilename);
            // decode and write
            binasm = fopen(binasmfilename, "w");
            if (binasm == NULL) {
               perror(binasmfilename);
               exit(1);
            }
            fprintf(binasm, "# generated by n64split\n.section .rodata\n\n.include \"%s\"\n", MACROS_FILE);
            switch (sec->type) {
               case TYPE_BLAST:
                  INFO("Section Blast: %d %s %X-%X\n", sec->subtype, sec->label, sec->start, sec->end);
                  sprintf(extension, "bc%d", sec->subtype);
                  break;
               case TYPE_MIO0:
                  INFO("Section MIO0: %s %X-%X\n", sec->label, sec->start, sec->end);
                  strcpy(extension, "mio0");
                  break;
               case TYPE_GZIP:
                  INFO("Section GZIP: %s %X-%X\n", sec->label, sec->start, sec->end);
                  strcpy(extension, "gz");
                  break;
               default:
                  break;
            }
            sprintf(outfilename, "%s.%s", start_label, extension);
            sprintf(binfilename, "%s/%s.bin", bin_dir, start_label);
            sprintf(mio0filename, "%s/%s", mio0_dir, outfilename);
            write_file(mio0filename, &data[sec->start], sec->end - sec->start);

            fprintf(fasm, "\n.align 4, 0x01\n");
            fprintf(fasm, ".global %s\n", start_label);
            fprintf(fasm, "%s:\n", start_label);
            fprintf(fasm, ".incbin \"%s/%s\"\n", MIO0_SUBDIR, outfilename);
            fprintf(fasm, "%s_end:\n", start_label);

            // append to Makefile
            strbuf_sprintf(&makeheader_mio0, " \\\n$(MIO0_DIR)/%s", outfilename);

            // TODO: use in-memory decompression?
            // extract compressed data
            switch (sec->type) {
               case TYPE_BLAST:
                  // TODO: make this configurable?
                  switch (sec->subtype) {
                     case 4: lut = &data[0x047480]; break;
                     case 5: lut = &data[0x0998E0]; break; // TODO: fix this
                     default: lut = data; break;
                  }
                  blast_decode_file(mio0filename, sec->subtype, binfilename, lut);
                  break;
               case TYPE_MIO0:
                  mio0_decode_file(mio0filename, 0, binfilename);
                  break;
               case TYPE_GZIP:
                  gzip_decode_file(mio0filename, 0, binfilename);
                  break;
               default:
                  break;
            }
            binfilelen = read_file(binfilename, &binfilecontents);

            // extract texture data
            if (sec->children) {
               unsigned int offset = 0;
	       unsigned int next_offset = 0;
               // TODO: add segment base to config file
	       const unsigned int segment_base = 0x07000000;
               unsigned int seg_address = segment_base + offset;
               fprintf(fmake, "$(MIO0_DIR)/%s.bin:", start_label);
               INFO("Extracting textures from %s\n", start_label);
               for (int t = 0; t < sec->child_count; t++) {
                  split_section *child = &sec->children[t];
                  texture *tex = &child->tex;
                  w = tex->width;
                  h = tex->height;
		  if (next_offset > child->start) {
                     ERROR("Error section overlap region %d (%X > %X)\n", t, next_offset, child->start);
		     exit(1);
		  }
		  if (next_offset != child->start) {
                     unsigned gap_len = child->start - next_offset;
		     INFO("Filling gap before region %d (%d bytes)\n", t, gap_len);
		     fprintf(binasm, "# Unknown region %06X-%06X [%X]\n", next_offset, child->start, gap_len);
		     while (gap_len > 0) {
                        int group_len = MIN(gap_len, 0x10);
			fprintf(binasm, ".byte ");
			fprint_hex_source(binasm, &binfilecontents[next_offset], group_len);
			fprintf(binasm, "\n");
			gap_len -= group_len;
			next_offset += group_len;
		     }
                  }
                  offset = tex->offset;
                  seg_address = segment_base + offset;
		  if (child->end) {
		     next_offset = child->end;
		  } else if (tex->format == TYPE_F3D_LIGHT) {
		     next_offset = child->start + 0x18;
		  } else { // assume texture
		     next_offset = child->start + w * h * tex->depth / 8;
		  }
                  fprintf(binasm, "\n");
                  switch (tex->format) {
                     case TYPE_TEX_IA:
                     {
                        sprintf(outfilename, "%s.%05X.ia%d", start_label, offset, tex->depth);
                        ia *img = raw2ia(&binfilecontents[offset], w, h, tex->depth);
                        if (img) {
                           sprintf(outfilepath, "%s/%s.png", texture_dir, outfilename);
                           ia2png(outfilepath, img, w, h);
                           free(img);
                           fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                        }
                        if (args->raw_texture && binfilelen > 0) {
                           INFO("Saving raw texture for %s\n", start_label);
                           int len = w*h*tex->depth/8;
                           sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                           write_file(outfilepath, &binfilecontents[offset], len);
                        }
                        fprintf(binasm, "texture_%08X: # 0x%08X\n", seg_address, seg_address);
                        fprintf(binasm, ".incbin \"%s\"\n", outfilename);
                        break;
                     }
                     case TYPE_TEX_I:
                     {
                        sprintf(outfilename, "%s.%05X.i%d", start_label, offset, tex->depth);
                        ia *img = raw2i(&binfilecontents[offset], w, h, tex->depth);
                        if (img) {
                           sprintf(outfilepath, "%s/%s.png", texture_dir, outfilename);
                           ia2png(outfilepath, img, w, h);
                           free(img);
                           fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                        }
                        if (args->raw_texture && binfilelen > 0) {
                           INFO("Saving raw texture for %s\n", start_label);
                           int len = w*h*tex->depth/8;
                           sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                           write_file(outfilepath, &binfilecontents[offset], len);
                        }
                        fprintf(binasm, "texture_%08X: # 0x%08X\n", seg_address, seg_address);
                        fprintf(binasm, ".incbin \"%s\"\n", outfilename);
                        break;
                     }
                     case TYPE_TEX_RGBA:
                     {
                        sprintf(outfilename, "%s.%05X.rgba%d", start_label, offset, tex->depth);
                        rgba *img = raw2rgba(&binfilecontents[offset], w, h, tex->depth);
                        if (img) {
                           sprintf(outfilepath, "%s/%s.png", texture_dir, outfilename);
                           rgba2png(outfilepath, img, w, h);
                           free(img);
                           fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                        }
                        if (args->raw_texture && binfilelen > 0) {
                           INFO("Saving raw texture for %s\n", start_label);
                           int len = w*h*tex->depth/8;
                           sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                           write_file(outfilepath, &binfilecontents[offset], len);
                        }
                        fprintf(binasm, "texture_%08X: # 0x%08X\n", seg_address, seg_address);
                        fprintf(binasm, ".incbin \"%s\"\n", outfilename);
                        break;
                     }
                     case TYPE_TEX_SKYBOX:
                     {
                        // read in grid of MxN 32x32 tiles and save them as M*31xN*31 image
                        rgba *img;
                        unsigned int sky_offset = offset;
                        int m, n;
                        int tx, ty;
                        m = w/32;
                        n = h/32;
                        img = malloc(w*h*sizeof(rgba));
                        w -= m; // adjust for overlap
                        h -= n;
                        for (ty = 0; ty < n; ty++) {
                           for (tx = 0; tx < m; tx++) {
                              rgba *tile = raw2rgba(&binfilecontents[sky_offset], 32, 32, tex->depth);
                              int cx, cy;
                              for (cy = 0; cy < 31; cy++) {
                                 for (cx = 0; cx < 31; cx++) {
                                    int out_off = 31*w*ty + 31*tx + w*cy + cx;
                                    int in_off = 32*cy+cx;
                                    img[out_off] = tile[in_off];
                                 }
                              }
                              free(tile);
                              sky_offset += 32*32*2;
                           }
                        }
                        sprintf(outfilename, "%s.%05X.skybox.png", start_label, offset);
                        sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                        rgba2png(outfilepath, img, w, h);
                        free(img);
                        fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                        break;
                     }
                     case TYPE_F3D_DL:
                     {
                        int sec_len = child->end - child->start;
                        fprintf(binasm, "f3d_%08X: # 0x%08X\n", seg_address, seg_address);
                        for (int o = 0; o < sec_len; o += 8) {
                           unsigned char cmd = binfilecontents[offset + o];
                           unsigned int second = read_u32_be(&binfilecontents[offset + o + 4]);
                           fprintf(binasm, ".word 0x%08X, ", read_u32_be(&binfilecontents[offset + o]));
                           switch (cmd) {
                              case 0x03: // light
                                 fprintf(binasm, "light_%08X\n", second);
                                 break;
                              case 0x04: // vertex
                                 fprintf(binasm, "vertex_%08X\n", second);
                                 break;
                              case 0x06: // f3d
                                 fprintf(binasm, "f3d_%08X\n", second);
                                 break;
                              case 0xFD: // texture
                                 fprintf(binasm, "texture_%08X\n", second);
                                 break;
                              default:
                                 fprintf(binasm, "0x%08X\n", second);
                                 break;
                           }
                        }
                        break;
                     }
                     case TYPE_F3D_LIGHT:
                     {
                        fprintf(binasm, "light_%08X: # 0x%08X\n", seg_address, seg_address);
                        fprintf(binasm, ".byte ");
                        fprint_hex_source(binasm, &binfilecontents[offset], 8);
                        fprintf(binasm, "\n");
                        fprintf(binasm, "light_%08X: # 0x%08X\n", seg_address + 8, seg_address + 8);
                        fprintf(binasm, ".byte ");
                        fprint_hex_source(binasm, &binfilecontents[offset + 8], 8);
                        fprintf(binasm, "\n.byte ");
                        fprint_hex_source(binasm, &binfilecontents[offset + 16], 8);
                        fprintf(binasm, "\n");
                        break;
                     }
                     case TYPE_F3D_VERTEX:
                     {
                        int sec_len = child->end - child->start;
                        fprintf(binasm, "vertex_%08X: # 0x%08X\n", seg_address, seg_address);
                        for (int o = 0; o < sec_len; o += 16) {
                           fprintf(binasm, "vertex ");
                           for (int h = 0; h < 6; h++) {
                              // X, Y, Z, UNUSED, U, V
                              if (h != 3) {
                                 fprintf(binasm, "%6d, ", read_s16_be(&binfilecontents[offset + o + h*2]));
                              }
                           }
                           // R, G, B, A
                           fprint_hex_source(binasm, &binfilecontents[offset + o + 12], 4);
                           fprintf(binasm, "\n");
                        }
                        break;
                     }
                     case TYPE_SM64_COLLISION:
                     {
                        int sec_len = 0;
                        sprintf(outfilename, "%s.%05X.collision", start_label, offset);
                        sprintf(outfilepath, "%s/%s.obj", model_dir, outfilename);
                        INFO("Generating collision model %s\n", outfilename);
                        sec_len = collision2obj(binfilename, offset, outfilepath, start_label, args->model_scale);
                        if (args->raw_texture && binfilelen > 0) {
                           INFO("Saving raw collision for %s\n", start_label);
                           sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                           write_file(outfilepath, &binfilecontents[offset], sec_len);
                        }
                        fprintf(binasm, "collision_%06X: # 0x%08X\n", seg_address, seg_address);
                        fprintf(binasm, ".incbin \"%s\"\n", outfilename);
                        break;
                     }
                     default:
                        ERROR("Don't know what to do with format %d\n", tex->format);
                        exit(1);
                  }
               }
               fprintf(fmake, "\n\t$(N64GRAPHICS) $@ $^\n\n");
            }

            // extract texture data
            if (args->large_texture) {
               INFO("Generating large texture for %s\n", start_label);
               w = 32;
               h = filesize(binfilename) / (w * (args->large_texture_depth / 8));
               rgba *img = raw2rgba(binfilecontents, w, h, args->large_texture_depth);
               if (img) {
                  sprintf(outfilename, "%s.ALL.png", start_label);
                  sprintf(outfilepath, "%s/%s", texture_dir, outfilename);
                  rgba2png(outfilepath, img, w, h);
                  free(img);
                  fprintf(fmake, " $(TEXTURE_DIR)/%s", outfilename);
                  img = NULL;
               }
            }
            // TODO: write files in correct order to avoid this
            // touch bin, then mio0 files so 'make' doesn't rebuild them right away
            touch_file(binfilename);
            touch_file(mio0filename);
            fclose(binasm);
            break;
         }
         case TYPE_SM64_LEVEL:
         {
            FILE *flevel;
            char levelfilename[FILENAME_MAX];
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "L%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            INFO("Section relocated level: %s %X-%X\n", start_label, sec->start, sec->end);
            sprintf(levelfilename, "%s.s", start_label);
            sprintf(outfilename, "%s/%s", LEVEL_SUBDIR, levelfilename);
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);

            // decode and write level data out
            flevel = fopen(outfilepath, "w");
            if (flevel == NULL) {
               perror(outfilepath);
               exit(1);
            }
            fprintf(flevel, "# level script %s from %X-%X\n\n", start_label, sec->start, sec->end);
            fprintf(flevel, ".section .mio0\n\n");
            fprintf(flevel, ".global %s\n", start_label);
            fprintf(flevel, ".align 4, 0x01\n");
            fprintf(flevel, "%s:\n", start_label);
            write_level(flevel, data, config, s, state);
            fprintf(flevel, "%s_end:\n", start_label);
            fclose(flevel);

            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(start_label, "L%06X", sec->start);
            } else {
               strcpy(start_label, sec->label);
            }
            fprintf(fasm, "\n.include \"%s\"\n", outfilename);
            // append to Makefile
            strbuf_sprintf(&makeheader_level, " \\\n$(LEVEL_DIR)/%s", levelfilename);
            break;
         }
         case TYPE_SM64_BEHAVIOR:
         {
            FILE *f_beh;
            char beh_filename[FILENAME_MAX];
            INFO("Section relocated behavior: %s %X-%X\n", sec->label, sec->start, sec->end);
            if (sec->label == NULL || sec->label[0] == '\0') {
               sprintf(beh_filename, "%06X.s", sec->start);
            } else {
               sprintf(beh_filename, "%s.s", sec->label);
            }
            sprintf(outfilename, "%s/%s", BEHAVIOR_SUBDIR, beh_filename);
            sprintf(outfilepath, "%s/%s", args->output_dir, outfilename);
            // decode and write level data out
            f_beh = fopen(outfilepath, "w");
            if (f_beh == NULL) {
               perror(outfilepath);
               exit(1);
            }
            write_behavior(f_beh, data, config, s, state);
            fclose(f_beh);

            fprintf(fasm, "\n.section .behavior, \"a\"\n");
            fprintf(fasm, "\n.global %s\n", sec->label);
            fprintf(fasm, ".global %s_end\n", sec->label);
            fprintf(fasm, "%s:\n", sec->label);
            fprintf(fasm, ".include \"%s\"\n", outfilename);
            fprintf(fasm, "%s_end:\n", sec->label);
            fprintf(fasm, "\n\n.section .mio0\n");

            // append to Makefile
            strbuf_sprintf(&makeheader_level, " \\\n%s/%s", BEHAVIOR_SUBDIR, beh_filename);
            break;
         }
         default:
            break;
      }
   }
   fprintf(fmake, "\n\n%s", makeheader_mio0.buf);
   fprintf(fmake, "\n\n%s", makeheader_level.buf);
   fprintf(fmake, "\n\n%s", makeheader_music.buf);

   // cleanup
   strbuf_free(&makeheader_mio0);
   strbuf_free(&makeheader_level);
   strbuf_free(&makeheader_music);
   fclose(fmake);
   fclose(fasm);

   // output top-level makefile
   sprintf(makefile_name, "%s/Makefile", args->output_dir);
   fmake = fopen(makefile_name, "w");
   fprintf(fmake, makefile_data);
   fclose(fmake);

   // output collision model material file
   sprintf(makefile_name, "%s/collision.mtl", model_dir);
   fmake = fopen(makefile_name, "w");
   fprintf(fmake, collision_mtl_data);
   fclose(fmake);

   generate_ld_script(args, config);
   generate_geo_macros(args);
}

static void print_usage(void)
{
   ERROR("Usage: n64split [-c CONFIG] [-k] [-m] [-o OUTPUT_DIR] [-s SCALE] [-t] [-v] [-V] ROM\n"
         "\n"
         "n64split v" N64SPLIT_VERSION ": N64 ROM splitter, resource ripper, disassembler\n"
         "\n"
         "Optional arguments:\n"
         " -c CONFIG     ROM configuration file (default: determine from checksum)\n"
         " -k            keep going as much as possible after error\n"
         " -m            merge related instructions in to pseudoinstructions\n"
         " -o OUTPUT_DIR output directory (default: {CONFIG.basename}.split)\n"
         " -r            output raw texture binaries\n"
         " -s SCALE      amount to scale models by (default: %.1f)\n"
         " -t            generate large texture for MIO0 blocks\n"
         " -v            verbose progress output\n"
         " -V            print version information\n"
         "\n"
         "File arguments:\n"
         " ROM        input ROM file\n",
         default_args.model_scale);
   exit(1);
}

static void print_version(void)
{
   ERROR("n64split v" N64SPLIT_VERSION ", using:\n"
         "  %s\n"
         "  %s\n"
         "  %s\n"
         "  %s\n",
         disasm_get_version(), n64graphics_get_read_version(), n64graphics_get_write_version(), config_get_version());
}

// parse command line arguments
static void parse_arguments(int argc, char *argv[], arg_config *config)
{
   int i;
   int file_count = 0;
   if (argc < 2) {
      print_usage();
      exit(1);
   }
   for (i = 1; i < argc; i++) {
      if (argv[i][0] == '-') {
         switch (argv[i][1]) {
            case 'c':
               if (++i >= argc) {
                  print_usage();
               }
               strcpy(config->config_file, argv[i]);
               break;
            case 'k':
               config->keep_going = true;
               break;
            case 'm':
               config->merge_pseudo = true;
               break;
            case 'o':
               if (++i >= argc) {
                  print_usage();
               }
               strcpy(config->output_dir, argv[i]);
               break;
            case 'r':
               config->raw_texture = true;
               break;
            case 's':
               if (++i >= argc) {
                  print_usage();
               }
               config->model_scale = strtof(argv[i], NULL);
               break;
            case 't':
               config->large_texture = true;
               break;
            case 'v':
               g_verbosity = 1;
               break;
            case 'V':
               print_version();
               exit(0);
               break;
            default:
               print_usage();
               break;
         }
      } else {
         if (file_count == 0) {
            strcpy(config->input_file, argv[i]);
         } else {
            // too many
            print_usage();
         }
         file_count++;
      }
   }
   if (file_count < 1) {
      print_usage();
   }
}

// Auto detect a config file based on the 2 checksums
static int detect_config_file(unsigned int c1, unsigned int c2, rom_config *config)
{
#define CONFIGS_DIR "configs"
   dir_list list;
   int config_ret;
   int ret_val = 0;
   int i;

   dir_list_ext(CONFIGS_DIR, ".yaml", &list);

   for (i = 0; i < list.count; i++) {
      config_ret = config_parse_file(list.files[i], config);
      INFO("Checking config file '%s' (%X, %X)\n", list.files[i], config->checksum1, config->checksum2);
      if (config_ret == 0 && c1 == config->checksum1 && c2 == config->checksum2) {
         ERROR("Using config file: %s\n", list.files[i]);
         ret_val = 1;
         break;
      } else {
         config_free(config);
      }
   }

   dir_list_free(&list);

   return ret_val;
}

int main(int argc, char *argv[])
{
   arg_config args;
   rom_config config;
   disasm_state *state;
   long len;
   unsigned char *data;
   int ret_val;
   unsigned int size;
   float percent;
   int i;
   n64_rom_format rom_type;

   args = default_args;
   parse_arguments(argc, argv, &args);

   len = read_file(args.input_file, &data);

   if (len <= 0) {
      return 2;
   }

   // confirm valid N64 ROM
   rom_type = n64_rom_type(data, len);
   switch (rom_type) {
      case N64_ROM_Z64:
         break; // Z64 is expected format
      case N64_ROM_V64:
         // byte-swapped BADC format, swap to big-endian ABCD format for processing
         INFO("Byte-swapping ROM\n");
         swap_bytes(data, len);
         break;
      case N64_ROM_INVALID:
         ERROR("This does not appear to be a valid N64 ROM\n");
         if (!args.keep_going) {
            exit(1);
         }
         break;
   }

   // if no config file supplied, find the right one
   if (0 == strcmp(args.config_file, "")) {
      ret_val = detect_config_file(read_u32_be(data+0x10), read_u32_be(data+0x14), &config);
      if (!ret_val) {
         ERROR("Error: could not find valid config file for '%s'\n", args.input_file);
         return 1;
      }
   } else {
      ret_val = config_parse_file(args.config_file, &config);
      if (ret_val != 0) {
         return 1;
      }
   }

   if (config_validate(&config, len)) {
      return 3;
   }

   // if no output directory specified, construct one from config file
   if (0 == strcmp(args.output_dir, "")) {
      sprintf(args.output_dir, "%s.split", config.basename);
      printf("Splitting into \"%s\" directory\n", args.output_dir);
   }

   // add config labels to disasm state labels
   state = disasm_state_init(ASM_GAS, 1);
   for (i = 0; i < config.label_count; i++) {
      disasm_label_add(state, config.labels[i].name, config.labels[i].ram_addr);
   }

   // first pass disassembler on each asm section
   INFO("Running first pass disassembler...\n");
   for (i = 0; i < config.section_count; i++) {
      if (config.sections[i].type == TYPE_ASM) {
         unsigned int start = config.sections[i].start;
         unsigned int end = config.sections[i].end;
         unsigned int vaddr = config.sections[i].vaddr;
         printf("First pass of section:%s\n",  config.sections[i].label);
         if (end <= (unsigned int)len) {
            mipsdisasm_pass1(data, start, end - start, vaddr, state);
         } else {
            ERROR("Trying to disassemble past end of file (%X > %X)\n", end, (unsigned int)len);
            exit(1);
         }
      }
   }

   // split the ROM
   INFO("Splitting ROM...\n");
   split_file(data, len, &args, &config, state);

   // print some stats
   printf("\nROM split statistics:\n");
   size = 0;
   for (i = 0; i < config.section_count; i++) {
      if (config.sections[i].type != TYPE_BIN) {
         size += config.sections[i].end - config.sections[i].start;
      }
   }
   percent = (float)(100 * size) / (float)(len);
   printf("Total decoded section size:  %X/%lX (%.2f%%) (i.e sections that are not .bin)\n", size, len, percent);
   size = 0;

   return 0;
}
